/* TRIỆU PHÚ HỌC ĐƯỜNG — ACTION/ENGINE FIX 1.0 */
(function(){'use strict';
function qs(s){return document.querySelector(s)}
function qsa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function subjectLabel(x){return {math:'➗ Toán',vietnamese:'📖 Tiếng Việt',science:'🔬 Khoa học',history:'🌏 Lịch sử & Địa lí'}[x]||x}
function norm(x){return String(x==null?'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[\s_\-&/]+/g,'').toUpperCase()}
function subject(x){var s=norm(x);if(s==='TOAN'||s==='MATH')return'math';if(s==='TV'||s==='TIENGVIET'||s==='VIETNAMESE')return'vietnamese';if(s==='KH'||s==='KHOAHOC'||s==='SCIENCE')return'science';if(s==='LSDL'||s==='LSDIALI'||s==='LICHSUDIALI'||s==='HISTORY'||s==='HISTORYGEOGRAPHY')return'history';return String(x||'').toLowerCase()}
var state={idx:0,score:0,used:{},selected:[],current:null,locked:false,help:{'5050':false,poll:false,change:false},timer:null,playerUsed:{}};
try{state.playerUsed=JSON.parse(localStorage.getItem('trieu_phu_hoc_duong_players_used')||'{}')||{}}catch(e){state.playerUsed={}}
function data(){return Array.isArray(window.GAME_QUESTIONS)?window.GAME_QUESTIONS:[]}
function students(){return window.GameData&&window.GameData.getStudents?window.GameData.getStudents():[]}
function fillStudents(){var s=qs('#student'),list=students();if(!s)return;s.innerHTML='';list.forEach(function(x){var id=String(x.id||x.studentCode||x.studentId||x.name||x.studentName||'');var o=document.createElement('option');o.value=id;o.textContent=x.name||x.studentName||id;s.appendChild(o)});if(!s.options.length){var o=document.createElement('option');o.value='guest';o.textContent='Học sinh chưa đồng bộ — chơi thử';s.appendChild(o)}}
function nextPlayer(){var list=students();if(!list.length){if(window.GameData&&window.GameData.loadStudents){window.GameData.loadStudents().then(nextPlayer)}return}var avail=list.filter(function(x){var id=String(x.id||x.studentCode||x.studentId||x.name||x.studentName||'');return id&&!state.playerUsed[id]});if(!avail.length){state.playerUsed={};try{localStorage.removeItem('trieu_phu_hoc_duong_players_used')}catch(e){}avail=list.slice()}var x=avail[Math.floor(Math.random()*avail.length)],id=String(x.id||x.studentCode||x.studentId||x.name||x.studentName||'');state.playerUsed[id]=true;try{localStorage.setItem('trieu_phu_hoc_duong_players_used',JSON.stringify(state.playerUsed))}catch(e){}fillStudents();var s=qs('#student');if(s)s.value=id;var d=qs('#nextPlayerDisplay');if(d)d.textContent='🎉 Người chơi tiếp theo: '+(x.name||x.studentName||id)}
window.nextPlayer=nextPlayer;
function pool(){var mode=qs('#gameMode'),sub=qs('#subject'),ch=qs('#chapter'),lv=qs('#level');var m=mode?mode.value:'bySubject',sv=subject(sub?sub.value:'math'),cv=ch?ch.value:'',l=lv?lv.value:'ALL';var p=data().filter(function(q){if(q.status&&String(q.status).toUpperCase()!=='ACTIVE')return false;if(m!=='mixed'&&subject(q.subject)!==sv)return false;if(m!=='mixed'&&cv&&String(q.chapter||'').trim()!==cv)return false;if(l!=='ALL'&&q.level!==l)return false;return true});var fresh=p.filter(function(q){return !state.used[q.id]});return fresh.length?fresh:p}
function renderQuestion(){clearTimeout(state.timer);state.locked=false;var p=pool(),q=qs('#question'),a=qs('#answers'),e=qs('#explanation');if(!p.length){q.textContent='❌ Không có câu hỏi phù hợp.';a.innerHTML='';return}state.current=p[Math.floor(Math.random()*p.length)];state.used[state.current.id]=true;state.selected.push(state.current.id);q.textContent=state.current.question;a.innerHTML='';(state.current.options||[]).forEach(function(t,i){var b=document.createElement('button');b.type='button';b.textContent=String.fromCharCode(65+i)+'. '+t;b.onclick=function(){answer(i)};a.appendChild(b)});e.textContent='';qs('#counter').textContent='Câu '+(state.idx+1)+'/15';qs('#score').textContent=state.score+' điểm'}
function answer(i){if(state.locked||!state.current)return;state.locked=true;var q=state.current,bs=qsa('#answers button'),correct=i===Number(q.correctAnswer);bs.forEach(function(b){b.disabled=true});if(bs[i])bs[i].style.outline='3px solid '+(correct?'#16a34a':'#dc2626');if(!correct&&bs[q.correctAnswer])bs[q.correctAnswer].style.outline='3px solid #16a34a';if(correct)state.score+=Number(q.points||1)*10;var e=qs('#explanation'),base=(correct?'✅ Chính xác! ':'❌ Chưa chính xác. ')+(q.explanation||'');e.textContent=base;var left=10;e.textContent=base+'  ⏱️ Câu tiếp theo sau 10 giây…';state.timer=setInterval(function(){left--;if(left>0)e.textContent=base+'  ⏱️ Câu tiếp theo sau '+left+' giây…'},1000);setTimeout(function(){clearInterval(state.timer);state.idx++;if(state.idx>=15)finish();else renderQuestion()},10000)}
function start(){var bank=window.QuestionBank;if(bank&&!bank.ready){if(bank.load)bank.load();return}state.idx=0;state.score=0;state.used={};state.selected=[];state.current=null;state.help={'5050':false,poll:false,change:false};qs('#home').classList.add('hidden');qs('#result').classList.add('hidden');qs('#play').classList.remove('hidden');renderQuestion()}
function finish(){qs('#play').classList.add('hidden');qs('#result').classList.remove('hidden');var s=qs('#student'),studentId=s?s.value:'guest',mode=qs('#gameMode'),sub=qs('#subject'),ch=qs('#chapter'),lv=qs('#level');var total=15,correct=Math.round(state.score/10);var r={id:'GAME_'+Date.now(),studentId:studentId,subject:mode&&mode.value==='mixed'?'mixed':(sub?sub.value:'math'),chapter:mode&&mode.value==='mixed'?'ALL':(ch?ch.value:'ALL'),level:lv?lv.value:'ALL',totalQuestions:total,correctAnswers:correct,wrongAnswers:total-correct,score:state.score,date:new Date().toISOString(),questionIds:state.selected,helpUsed:state.help};if(window.GameData&&window.GameData.saveResult)window.GameData.saveResult(r);qs('#resultText').innerHTML='<p class="result-good">'+state.score+' điểm</p><p>Đã hoàn thành '+total+'/15 câu.</p>'}
function home(){clearTimeout(state.timer);qs('#play').classList.add('hidden');qs('#result').classList.add('hidden');qs('#home').classList.remove('hidden');fillStudents()}
function view(title,html){home();qs('#home').classList.add('hidden');var old=qsa('.game-view');old.forEach(function(x){x.remove()});var v=document.createElement('section');v.className='panel game-view';v.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><h2>'+title+'</h2><button type="button" data-local-back>← Trang chủ</button></div>'+html;document.querySelector('.app').appendChild(v);v.querySelector('[data-local-back]').onclick=function(){v.remove();qs('#home').classList.remove('hidden')};return v}
function leaderboard(){var rows=window.GameData&&window.GameData.getResults?window.GameData.getResults():[];rows.sort(function(a,b){return Number(b.score||0)-Number(a.score||0)});var html=rows.length?'<div class="table-wrap"><table><thead><tr><th>#</th><th>Học sinh</th><th>Môn</th><th>Chương</th><th>Điểm</th></tr></thead><tbody>'+rows.slice(0,20).map(function(r,i){return'<tr><td>'+(i+1)+'</td><td>'+esc(r.studentId)+'</td><td>'+subjectLabel(r.subject)+'</td><td>'+esc(r.chapter||'Tổng hợp')+'</td><td>'+Number(r.score||0)+'</td></tr>'}).join('')+'</tbody></table></div>':'<p>Chưa có kết quả chơi.</p>';view('🏆 Bảng xếp hạng',html)}
function results(){var rows=window.GameData&&window.GameData.getResults?window.GameData.getResults():[];var html=rows.length?rows.slice().reverse().map(function(r){return'<p><strong>'+esc(r.studentId)+'</strong> — '+subjectLabel(r.subject)+' — '+esc(r.chapter||'Tổng hợp')+' — '+Number(r.score||0)+' điểm</p>'}).join(''):'<p>Chưa có kết quả học tập.</p>';view('📈 Kết quả học tập',html)}
function bank(){var rows=data();var html='<p><strong>'+rows.length+'</strong> câu hỏi từ BO_CAU_HOI.</p>';view('🗂️ Ngân hàng câu hỏi',html)}
function admin(){view('⚙️ Quản trị giáo viên','<p>Ngân hàng câu hỏi: BO_CAU_HOI. Bộ lọc: Môn → Chương → Mức độ.</p>')}
function bind(){qsa('[data-action]').forEach(function(b){b.onclick=null});var map={start:start,leaderboard:leaderboard,results:results,bank:bank,admin:admin,home:home};qsa('[data-action]').forEach(function(b){var fn=map[b.getAttribute('data-action')];if(fn)b.addEventListener('click',fn)});var nb=qs('#nextPlayerButton');if(nb){nb.onclick=null;nb.addEventListener('click',nextPlayer)};var mode=qs('#gameMode'),sub=qs('#subject');if(mode)mode.addEventListener('change',function(){if(window.refreshChapterFilter)window.refreshChapterFilter()});if(sub)sub.addEventListener('change',function(){if(window.refreshChapterFilter)window.refreshChapterFilter()});fillStudents()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(bind,0)});else setTimeout(bind,0);
})();
