/* TRIỆU PHÚ HỌC ĐƯỜNG — CHAPTER FILTER FIX 3.0 */
(function(){'use strict';
if(window.__LH_CHAPTER_FIX_30__)return;window.__LH_CHAPTER_FIX_30__=true;
function text(v){return String(v==null?'':v).replace(/^\uFEFF/,'').trim().replace(/\s+/g,' ')}
function norm(v){return text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/Đ/g,'D').replace(/đ/g,'d').replace(/[\s_\-&/.:]+/g,'').toUpperCase()}
function subject(v,id){var s=norm(v),i=norm(id);if(/^(TOAN|MATH|MATHEMATICS)$/.test(s)||/TOAN/.test(i))return'math';if(/^(TV|TIENGVIET|VIETNAMESE)$/.test(s)||/TIENGVIET/.test(i))return'vietnamese';if(/^(KH|KHOAHOC|KHOAHOC5|SCIENCE|NATURALSCIENCE)$/.test(s)||/KHOAHOC/.test(i)||/^KH[-_]/.test(i))return'science';if(/^(LSDL|LSDIALI|LSDIALI5|LICHSUDIALI|LICHSUVADIALI|HISTORY|HISTORYGEOGRAPHY|HISTORYANDGEOGRAPHY)$/.test(s)||/LICHSUDIALI/.test(i)||/LSDIALI/.test(i)||/^LS[-_]?DL/.test(i))return'history';return s.toLowerCase()}
function chapterFromId(id){var s=norm(id),m=s.match(/(?:^|-)C(\d{1,2})(?:-|$)/);return m?'Chủ đề '+String(Number(m[1])):''}
function chapterValue(q){if(!q)return'';var a=[q.chapter,q.Chuong,q.ChuDe,q.chude,q.topic,q.Topic,q.topicName,q.chapterName,q.subjectTopic];for(var i=0;i<a.length;i++){var v=text(a[i]);if(v)return v}return chapterFromId(q.id||q.ID||'')}
function refresh(){var sel=document.getElementById('chapter'),sub=document.getElementById('subject'),mode=document.getElementById('gameMode');if(!sel||!sub)return;if(mode&&mode.value==='mixed'){sel.disabled=true;sel.innerHTML='<option value="">🌐 Tổng hợp 4 môn — không chia chủ đề</option>';return}var qs=Array.isArray(window.GAME_QUESTIONS)?window.GAME_QUESTIONS:[];if(!qs.length){sel.disabled=true;sel.innerHTML='<option value="">⏳ Đang tải chủ đề...</option>';return}var target=subject(sub.value,''),map={};qs.forEach(function(q){if(subject(q.subject||q.Mon,q.id||q.ID)!==target)return;var ch=chapterValue(q);if(ch)map[ch]=1});var keys=Object.keys(map).sort(function(a,b){return a.localeCompare(b,'vi',{numeric:true,sensitivity:'base'})});sel.disabled=false;sel.innerHTML='';if(!keys.length){sel.innerHTML='<option value="">⚠️ Chưa nhận diện được chủ đề cho môn này</option>';return}var first=document.createElement('option');first.value='';first.textContent='📚 Chọn chủ đề / chương';sel.appendChild(first);keys.forEach(function(ch){var o=document.createElement('option');o.value=ch;o.textContent='📘 '+ch;sel.appendChild(o)})}
window.refreshChapterFilter=refresh;
function boot(){refresh();var s=document.getElementById('subject'),m=document.getElementById('gameMode');if(s)s.addEventListener('change',function(){setTimeout(refresh,0)});if(m)m.addEventListener('change',function(){setTimeout(refresh,0)});var n=0,t=setInterval(function(){refresh();if(++n>=60)clearInterval(t)},500);window.addEventListener('questionBankReady',function(){setTimeout(refresh,0)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
