/* TRIỆU PHÚ HỌC ĐƯỜNG — CHAPTER FILTER FIX 2.0 */
(function(){'use strict';
if(window.__LH_CHAPTER_FIX_20__)return;window.__LH_CHAPTER_FIX_20__=true;
function text(v){return String(v==null?'':v).replace(/^\uFEFF/,'').trim().replace(/\s+/g,' ')}
function norm(v){return text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/Đ/g,'D').replace(/đ/g,'d').replace(/[\s_\-&/.:]+/g,'').toUpperCase()}
function subject(v){var s=norm(v);if(/^(TOAN|MATH|MATHEMATICS)$/.test(s))return'math';if(/^(TV|TIENGVIET|VIETNAMESE)$/.test(s))return'vietnamese';if(/^(KH|KHOAHOC|KHOAHOC5|SCIENCE|NATURALSCIENCE)$/.test(s))return'science';if(/^(LSDL|LSDIALI|LSDIALI5|LICHSUDIALI|LICHSUVADIALI|LICHSUDIALI5|HISTORY|HISTORYGEOGRAPHY|HISTORYANDGEOGRAPHY|HISTORYGEOGRAPHY5)$/.test(s))return'history';if(s.indexOf('LICHSUVADIALI')>=0||s.indexOf('LICHSUDIALI')>=0||s.indexOf('LSDIALI')>=0||s==='LSDL')return'history';if(s.indexOf('KHOAHOC')>=0||s==='KH')return'science';return s.toLowerCase()}
function chapterValue(q){if(!q)return'';var candidates=[q.chapter,q.Chuong,q.topic,q.Topic,q.chude,q.chuDe,q.ChuDe,q.subjectTopic,q.topicName,q.chapterName];for(var i=0;i<candidates.length;i++){var v=text(candidates[i]);if(v)return v}return''}
function refresh(){var sel=document.getElementById('chapter'),sub=document.getElementById('subject'),mode=document.getElementById('gameMode');if(!sel||!sub)return;if(mode&&mode.value==='mixed'){sel.disabled=true;sel.innerHTML='<option value="">🌐 Tổng hợp 4 môn — không chia chương</option>';return;}var qs=Array.isArray(window.GAME_QUESTIONS)?window.GAME_QUESTIONS:[];if(!qs.length){sel.disabled=true;sel.innerHTML='<option value="">⏳ Đang tải chủ đề...</option>';return;}var target=subject(sub.value),map={};qs.forEach(function(q){if(subject(q.subject)!==target)return;var ch=chapterValue(q);if(!ch)return;map[ch]=1;});var keys=Object.keys(map).sort(function(a,b){return a.localeCompare(b,'vi',{numeric:true,sensitivity:'base'});});sel.disabled=false;sel.innerHTML='';if(!keys.length){sel.innerHTML='<option value="">⚠️ Chưa nhận diện được chủ đề cho môn này</option>';return;}var first=document.createElement('option');first.value='';first.textContent='📚 Chọn chủ đề / chương';sel.appendChild(first);keys.forEach(function(ch){var o=document.createElement('option');o.value=ch;o.textContent='📘 '+ch;sel.appendChild(o);});}
window.refreshChapterFilter=refresh;
function boot(){refresh();var s=document.getElementById('subject'),m=document.getElementById('gameMode');if(s)s.addEventListener('change',function(){setTimeout(refresh,0)});if(m)m.addEventListener('change',function(){setTimeout(refresh,0)});var n=0,t=setInterval(function(){refresh();if(++n>=40)clearInterval(t)},500);window.addEventListener('questionBankReady',function(){setTimeout(refresh,0)});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
