/* TRIỆU PHÚ HỌC ĐƯỜNG — CHAPTER FILTER FIX 1.0 */
(function(){'use strict';
function norm(v){return String(v==null?'':v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[\s_\-&/]+/g,'').toUpperCase();}
function subject(v){var s=norm(v);if(['TOAN','MATH','MATHEMATICS'].indexOf(s)>=0)return'math';if(['TV','TIENGVIET','VIETNAMESE'].indexOf(s)>=0)return'vietnamese';if(['KH','KHOAHOC','SCIENCE'].indexOf(s)>=0)return'science';if(['LSDL','LSDIALI','LICHSUDIALI','HISTORY','HISTORYGEOGRAPHY'].indexOf(s)>=0)return'history';return s.toLowerCase();}
function refresh(){var sel=document.getElementById('chapter'),sub=document.getElementById('subject'),mode=document.getElementById('gameMode');if(!sel||!sub)return;if(mode&&mode.value==='mixed'){sel.disabled=true;sel.innerHTML='<option value="">🌐 Tổng hợp 4 môn — không chia chương</option>';return;}var qs=Array.isArray(window.GAME_QUESTIONS)?window.GAME_QUESTIONS:[];if(!qs.length){sel.disabled=true;sel.innerHTML='<option value="">⏳ Đang tải chương...</option>';return;}var target=subject(sub.value),map={};qs.forEach(function(q){if(subject(q.subject)!==target)return;var ch=String(q.chapter==null?'':q.chapter).trim();if(ch)map[ch]=1;});var keys=Object.keys(map).sort(function(a,b){return a.localeCompare(b,'vi',{numeric:true,sensitivity:'base'});});sel.disabled=false;sel.innerHTML='';if(!keys.length){sel.innerHTML='<option value="">⚠️ Chưa có chương cho môn này</option>';return;}var first=document.createElement('option');first.value='';first.textContent='📚 Chọn chương';sel.appendChild(first);keys.forEach(function(ch){var o=document.createElement('option');o.value=ch;o.textContent='📘 '+ch;sel.appendChild(o);});}
window.refreshChapterFilter=refresh;
function boot(){refresh();var sub=document.getElementById('subject'),mode=document.getElementById('gameMode');if(sub)sub.addEventListener('change',function(){setTimeout(refresh,0);});if(mode)mode.addEventListener('change',function(){setTimeout(refresh,0);});var n=0,t=setInterval(function(){refresh();if(++n>=24)clearInterval(t);},500);window.addEventListener('questionBankReady',refresh);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
