/* ============================================================
   TRIỆU PHÚ HỌC ĐƯỜNG — SHARED DATA ADAPTER 2.2
   Nguồn học sinh duy nhất: Apps Script / Google Sheets.
   API Web App chính: MASTER-3.4-SHEET-CONFIRMED-SAFE.
   Không sửa HOC_SINH, không tạo roster thứ hai.
   Có fallback action để tương thích deployment cũ.
   ============================================================ */
(function(){'use strict';
var API_URL='https://script.google.com/macros/s/AKfycbxTPwf-jhrR8JOoKY5ZLuzlsDgcv3nWILtDPTrYNWZCEPpm2rkpXTn-sPAdFaUyy0z_uw/exec',studentsCache=[],lastApiAction='',API_VERSION='MASTER-3.4-SHEET-CONFIRMED-SAFE';
function text(v){return String(v==null?'':v).trim().replace(/\s+/g,' ')}
function key(v){return text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9]/g,'')}
function dateKey(v){var s=text(v);if(!s)return'';var m=s.match(/^(\d{4})[-\/.](\d{1,2})[-\/.](\d{1,2})/);if(m)return m[3].padStart(2,'0')+m[2].padStart(2,'0')+m[1];m=s.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})/);if(m)return m[1].padStart(2,'0')+m[2].padStart(2,'0')+m[3];return s.replace(/\D/g,'')}
function identity(s){return key(s.name)+'|'+dateKey(s.birthDate)+'|'+key(s.gender)}
function canonical(id){return /^STU_5C_2026_\d{3,4}$/i.test(text(id))}
function preferred(a,b){if(!a)return b;if(!b)return a;var ca=canonical(a.id),cb=canonical(b.id);if(cb&&!ca)return b;if(ca&&!cb)return a;return Number(a._row||999999)<=Number(b._row||999999)?a:b}
function dedupe(list){var by=new Map();(Array.isArray(list)?list:[]).filter(function(s){return s&&text(s.id||s.studentId||s.studentCode)&&text(s.name||s.studentName)}).forEach(function(s){var n={id:text(s.id||s.studentId||s.studentCode),studentCode:text(s.studentCode||s.id||s.studentId),name:text(s.name||s.studentName),gender:text(s.gender),birthDate:text(s.birthDate||s.dateOfBirth),status:text(s.status)||'active',parentName:text(s.parentName),phone:text(s.phone),address:text(s.address),note:text(s.note),shareEnabled:s.shareEnabled!==false,createdAt:text(s.createdAt),updatedAt:text(s.updatedAt),_row:s.row||s._row||999999};var k=identity(n),old=by.get(k);by.set(k,old?preferred(old,n):n)});return Array.from(by.values()).sort(function(a,b){return key(a.name).localeCompare(key(b.name),'vi')||Number(a._row)-Number(b._row)})}
function extractStudents(data){if(!data)return[];if(Array.isArray(data))return data;if(Array.isArray(data.students))return data.students;if(data.data&&Array.isArray(data.data.students))return data.data.students;if(Array.isArray(data.HOC_SINH))return data.HOC_SINH;if(data.data&&Array.isArray(data.data.HOC_SINH))return data.data.HOC_SINH;return[]}
function parse(raw,action){var data;try{data=JSON.parse(raw)}catch(_){throw new Error('Google API trả dữ liệu không phải JSON ['+action+']')};if(!data||data.ok!==true)throw new Error((data&&data.error)||'Action không được hỗ trợ: '+action);var list=dedupe(extractStudents(data));if(!list.length)throw new Error('Google không trả danh sách học sinh ['+action+']');return list}
function request(action){return fetch(API_URL+'?action='+encodeURIComponent(action)+'&t='+Date.now(),{method:'GET',cache:'no-store',redirect:'follow',headers:{'Accept':'application/json'}}).then(function(r){if(!r.ok)throw new Error('Google API HTTP '+r.status+' ['+action+']');return r.text()}).then(function(raw){return parse(raw,action)})}
function loadStudents(){var actions=['get_students','students','roster','get_roster','getstudents','getStudents'];var i=0,last=null;function next(){if(i>=actions.length)return Promise.reject(last||new Error('Không có action GET tương thích với Web App'));var action=actions[i++];return request(action).then(function(list){lastApiAction=action;studentsCache=list;window.students=list.slice();try{window.dispatchEvent(new CustomEvent('gameRosterReady',{detail:{count:list.length,source:'google-sheets',action:action,apiVersion:API_VERSION}}))}catch(_){}return list}).catch(function(err){last=err;return next()})}return next()}
function activeStudents(){return dedupe(studentsCache.length?studentsCache:(Array.isArray(window.students)?window.students:[])).filter(function(s){return String(s.status).toLowerCase()!=='inactive'&&s.status!==false})}
window.GameData={API_URL:API_URL,API_VERSION:API_VERSION,getLastApiAction:function(){return lastApiAction},getStudents:function(){return activeStudents()},loadStudents:loadStudents,reloadStudents:function(){studentsCache=[];try{window.students=[]}catch(_){}return loadStudents()},saveResult:function(result){var keyName='QL_GAME_RESULTS_2026_2027',rows=[];try{rows=JSON.parse(localStorage.getItem(keyName)||'[]')}catch(_){}rows.push(result);localStorage.setItem(keyName,JSON.stringify(rows));return true},getResults:function(){try{return JSON.parse(localStorage.getItem('QL_GAME_RESULTS_2026_2027')||'[]')}catch(_){return []}}};
function boot(){if(window.GameData.getStudents().length)return;window.GameData.loadStudents().catch(function(err){console.warn('GameData Google:',err);try{window.dispatchEvent(new CustomEvent('gameRosterError',{detail:{message:err.message,api:API_URL}}))}catch(_){} })}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
