/* TRIỆU PHÚ HỌC ĐƯỜNG — GAME ENGINE 4.4 MOBILE + ROULETTE */
(function(){'use strict';
var questions=[],idx=0,score=0,used={},current=null,locked=false,questionTimer=null,answerTransitionInterval=null,answerTransitionTimeout=null;
var home,play,result,student,subject,chapter,level,mode,nextDisplay;
var playersUsed={};
var helpUsed={"5050":false,"poll":false,"change":false};
function $(id){return document.getElementById(id)}
function normalize(v){return String(v==null?'':v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/Đ/g,'D').replace(/đ/g,'d').replace(/[\s_\-&/]+/g,'').toUpperCase()}
function sub(v){var s=normalize(v);if(['TOAN','MATH','MATHEMATICS'].indexOf(s)>=0)return'math';if(['TV','TIENGVIET','VIETNAMESE'].indexOf(s)>=0)return'vietnamese';if(['KH','KHOAHOC','SCIENCE'].indexOf(s)>=0)return'science';if(['LSDL','LSDIALI','LICHSUDIALI','LICHSUVADIALI','HISTORY','HISTORYGEOGRAPHY','HISTORYANDGEOGRAPHY'].indexOf(s)>=0)return'history';return s.toLowerCase()}
function chapterValue(q){if(!q)return'';var v=q.chapter!=null?q.chapter:(q.Chuong!=null?q.Chuong:(q.topic!=null?q.topic:''));return String(v==null?'':v).normalize('NFC').replace(/[\uFEFF]/g,'').trim().replace(/\s+/g,' ')}
function chapterKey(v){return String(v==null?'':v).normalize('NFC').replace(/[\uFEFF]/g,'').trim().replace(/\s+/g,' ')}
function studentId(s){return String(s&& (s.id||s.studentId||s.studentCode||s.name||s.studentName) || '').trim()}
function studentName(s){return String(s&& (s.name||s.studentName||s.id||s.studentId||'') || '').trim()}
function loadPlayers(){var list=window.GameData&&window.GameData.getStudents?window.GameData.getStudents():[];if(list.length){fillStudents(list);return Promise.resolve(list)}if(window.GameData&&window.GameData.loadStudents)return Promise.resolve(window.GameData.loadStudents()).then(function(){var a=window.GameData.getStudents();fillStudents(a);return a});return Promise.resolve([])}
function fillStudents(list){if(!student)return;var old=student.value;student.innerHTML='';(list||[]).forEach(function(s){var id=studentId(s);if(!id)return;var o=document.createElement('option');o.value=id;o.textContent=studentName(s);student.appendChild(o)});if(!student.options.length){var o=document.createElement('option');o.value='guest';o.textContent='Học sinh chưa đồng bộ — chơi thử';student.appendChild(o)}if(old&&Array.prototype.some.call(student.options,function(o){return o.value===old}))student.value=old}
function roulettePanel(){var box=$('studentRoulette');if(box)return box;box=document.createElement('div');box.id='studentRoulette';box.setAttribute('role','status');box.setAttribute('aria-live','polite');box.style.cssText='display:none;margin:12px auto 0;padding:14px 18px;border-radius:16px;text-align:center;background:linear-gradient(135deg,#111827,#1e3a8a);color:#fff;box-shadow:0 10px 28px rgba(0,0,0,.22);font-size:clamp(18px,5vw,28px);font-weight:800;min-height:34px;align-items:center;justify-content:center;overflow:hidden';var spin=document.createElement('div');spin.id='studentRouletteName';spin.textContent='🎲 Chuẩn bị chọn người chơi…';box.appendChild(spin);if(nextDisplay&&nextDisplay.parentNode)nextDisplay.parentNode.insertBefore(box,nextDisplay);else if(home)home.appendChild(box);return box}
function roulette(list,done){var box=roulettePanel(),nameBox=$('studentRouletteName'),pool=list.slice(),start=performance.now(),duration=5000,step=0,chosen=null;box.style.display='flex';if(window.LHGameTheme&&window.LHGameTheme.thinking)window.LHGameTheme.thinking();function tick(now){var elapsed=now-start;if(elapsed>=duration){chosen=pool[Math.floor(Math.random()*pool.length)];nameBox.textContent='🏆 '+studentName(chosen);student.value=studentId(chosen);box.style.transform='scale(1.04)';setTimeout(function(){box.style.transform='scale(1)';},160);if(window.LHGameTheme&&window.LHGameTheme.select)window.LHGameTheme.select();setTimeout(function(){box.style.display='none';done(chosen)},650);return}var progress=elapsed/duration;var delay=55+Math.floor(progress*260);var shown=pool[step%pool.length];nameBox.textContent='🎲 '+studentName(shown);step++;setTimeout(function(){requestAnimationFrame(tick)},delay)}requestAnimationFrame(tick)}
function nextPlayer(){if(nextPlayer._busy)return;nextPlayer._busy=true;var btn=$('nextPlayerButton');if(btn){btn.disabled=true;btn.setAttribute('aria-busy','true');btn.textContent='🎲 ĐANG CHỌN…'}loadPlayers().then(function(list){if(!list.length){alert('Chưa có danh sách học sinh để chọn.');return}var available=list.filter(function(s){var id=studentId(s);return id&&!playersUsed[id]});if(!available.length){if(!confirm('🎉 Đã chọn hết học sinh trong vòng này. Bắt đầu vòng mới?'))return;playersUsed={};try{localStorage.removeItem('trieu_phu_hoc_duong_players_used')}catch(e){}available=list.slice()}roulette(available,function(s){var id=studentId(s);playersUsed[id]=true;try{localStorage.setItem('trieu_phu_hoc_duong_players_used',JSON.stringify(playersUsed))}catch(e){}if(student)student.value=id;if(nextDisplay)nextDisplay.textContent='🎉 Người chơi tiếp theo: '+studentName(s);});}).catch(function(e){alert('Không tải được danh sách học sinh: '+e.message)}).finally(function(){setTimeout(function(){nextPlayer._busy=false;if(btn){btn.disabled=false;btn.removeAttribute('aria-busy');btn.textContent='🎲 NGƯỜI CHƠI TIẾP THEO'}},5800)})}
function chapters(){if(!chapter)return;var m=mode?mode.value:'bySubject';if(m==='mixed'){chapter.disabled=true;chapter.innerHTML='<option value="">🌐 Tổng hợp 4 môn — không chia chương</option>';return}var target=sub(subject?subject.value:'math'),set={};questions.forEach(function(q){if(sub(q.subject)!==target)return;var c=chapterValue(q);if(c)set[c]=1});var keys=Object.keys(set).sort(function(a,b){return a.localeCompare(b,'vi',{numeric:true,sensitivity:'base'})});chapter.innerHTML='';if(!keys.length){chapter.disabled=true;chapter.innerHTML='<option value="">⚠️ Chưa có chương cho môn này</option>';return}var first=document.createElement('option');first.value='';first.textContent='📚 Chọn chương';chapter.appendChild(first);keys.forEach(function(c){var o=document.createElement('option');o.value=c;o.textContent='📘 '+c;chapter.appendChild(o)});chapter.disabled=false}
function syncQuestions(){questions=Array.isArray(window.GAME_QUESTIONS)?window.GAME_QUESTIONS:[];chapters()}
function pool(){var m=mode?mode.value:'bySubject',s=sub(subject?subject.value:'math'),c=chapterKey(chapter?chapter.value:''),lv=level?level.value:'ALL';return questions.filter(function(q){if(q.status&&String(q.status).toUpperCase()!=='ACTIVE')return false;if(m!=='mixed'&&sub(q.subject)!==s)return false;if(m!=='mixed'&&c&&chapterKey(chapterValue(q))!==c)return false;if(lv!=='ALL'&&q.level!==lv)return false;return true})}
function clearQuestionTimers(){if(questionTimer){clearInterval(questionTimer);questionTimer=null}if(answerTransitionInterval){clearInterval(answerTransitionInterval);answerTransitionInterval=null}if(answerTransitionTimeout){clearTimeout(answerTransitionTimeout);answerTransitionTimeout=null}}
function stopQuestionTimer(){if(questionTimer){clearInterval(questionTimer);questionTimer=null}}
function updateQuestionTimer(value){var el=$('timer'),box=$('timerBox'),status=$('timerStatus'),remaining=Math.max(0,value),expired=remaining<=0;if(el)el.textContent=String(remaining);if(box){box.classList.toggle('urgent',remaining<=10);box.setAttribute('aria-label',expired?'Hết thời gian':'Còn '+remaining+' giây suy nghĩ')}if(status){status.hidden=!expired;status.setAttribute('aria-hidden',expired?'false':'true')}}
function startQuestionTimer(){stopQuestionTimer();var left=60;updateQuestionTimer(left);questionTimer=setInterval(function(){left--;updateQuestionTimer(left);if(left<=0){stopQuestionTimer()}},1000)}
function showHome(){clearQuestionTimers();home.classList.remove('hidden');play.classList.add('hidden');result.classList.add('hidden');document.querySelectorAll('.game-view').forEach(function(x){x.remove()});syncQuestions()}
function renderQuestion(q){locked=false;clearQuestionTimers();current=q;$('counter').textContent='Câu '+(idx+1)+'/15';$('score').textContent=score+' điểm';$('question').textContent=q.question;var box=$('answers');box.innerHTML='';(q.options||[]).forEach(function(t,i){var b=document.createElement('button');b.type='button';b.textContent=String.fromCharCode(65+i)+'. '+t;b.dataset.i=i;b.onclick=function(){answer(i,false)};box.appendChild(b)});$('explanation').textContent='';updateHelpButtons();startQuestionTimer()}
function render(){var list=pool().filter(function(q){return !used[q.id]});if(!list.length)list=pool();if(!list.length){$('question').textContent='❌ Không có câu hỏi phù hợp với lựa chọn.';$('answers').innerHTML='';return}current=list[Math.floor(Math.random()*list.length)];used[current.id]=true;renderQuestion(current)}
function answer(i,timedOut){if(locked||!current)return;locked=true;stopQuestionTimer();var buttons=document.querySelectorAll('#answers button');buttons.forEach(function(b){b.disabled=true});var correct=Number(current.correctAnswer),ok=!timedOut&&i===correct;if(ok){score+=Number(current.points||1)*10;buttons[i].style.outline='3px solid #16a34a'}else{if(!timedOut&&buttons[i])buttons[i].style.outline='3px solid #dc2626';if(buttons[correct])buttons[correct].style.outline='3px solid #16a34a'}var correctText=(current.options&&current.options[correct]!=null)?String(current.options[correct]):'';var text=timedOut?'Bạn chưa kịp trả lời. Đáp án đúng: '+String.fromCharCode(65+correct)+(correctText?' — '+correctText:''):(ok?'✅ Chính xác! ':'❌ Chưa chính xác. ')+(current.explanation||'');$('explanation').textContent=text+'  ⏱️ Chuyển câu sau 10 giây…';var left=10;answerTransitionInterval=setInterval(function(){left--;if(left>0)$('explanation').textContent=text+'  ⏱️ Chuyển câu sau '+left+' giây…'},1000);answerTransitionTimeout=setTimeout(function(){if(answerTransitionInterval){clearInterval(answerTransitionInterval);answerTransitionInterval=null}answerTransitionTimeout=null;idx++;if(idx>=15)finish();else render()},10000)}
function updateHelpButtons(){document.querySelectorAll('[data-help]').forEach(function(b){var k=b.getAttribute('data-help');b.disabled=!!helpUsed[k]})}
function help5050(){if(helpUsed['5050']||locked||!current)return;helpUsed['5050']=true;var buttons=[].slice.call(document.querySelectorAll('#answers button'));var wrong=buttons.filter(function(b){return Number(b.dataset.i)!==Number(current.correctAnswer)&&!b.disabled});wrong.sort(function(){return Math.random()-.5}).slice(0,2).forEach(function(b){b.disabled=true;b.style.opacity='.35';b.style.textDecoration='line-through'});$('explanation').textContent='💡 50:50: Đã loại 2 đáp án sai.';updateHelpButtons();if(window.LHGameTheme)window.LHGameTheme.help('5050')}
function poll(){if(helpUsed.poll||locked||!current)return;helpUsed.poll=true;var c=Number(current.correctAnswer),v=[0,0,0,0],r=100;var wrong=[0,1,2,3].filter(function(i){return i!==c});wrong.forEach(function(i,n){var value=n===wrong.length-1?Math.floor(r*.35):Math.floor(Math.random()*Math.max(1,r*.55));v[i]=value;r-=value});v[c]=r;var total=v.reduce(function(a,b){return a+b},0)||100;v=v.map(function(x){return Math.round(x*100/total)});v[c]+=100-v.reduce(function(a,b){return a+b},0);$('explanation').innerHTML='👥 <b>Hỏi cả lớp:</b> A '+v[0]+'% • B '+v[1]+'% • C '+v[2]+'% • D '+v[3]+'%';updateHelpButtons();if(window.LHGameTheme)window.LHGameTheme.help('poll')}
function changeQuestion(){if(helpUsed.change||locked||!current)return;helpUsed.change=true;var candidates=pool().filter(function(q){return q.id!==current.id&&!used[q.id]});if(!candidates.length){$('explanation').textContent='⚠️ Không còn câu hỏi khác phù hợp.';updateHelpButtons();return}var n=candidates[Math.floor(Math.random()*candidates.length)];used[n.id]=true;renderQuestion(n);$('explanation').textContent='🔄 Đã đổi sang câu hỏi mới.';updateHelpButtons();if(window.LHGameTheme)window.LHGameTheme.change()}
function bindHelp(){document.querySelectorAll('[data-help]').forEach(function(b){b.onclick=function(){var k=b.getAttribute('data-help');if(k==='5050')help5050();else if(k==='poll')poll();else if(k==='change')changeQuestion()}});updateHelpButtons()}
function start(){syncQuestions();if(window.QuestionBank&&!window.QuestionBank.ready){if(window.QuestionBank.load)window.QuestionBank.load();setTimeout(start,700);return}if(!questions.length){alert('Ngân hàng câu hỏi chưa tải xong.');return}idx=0;score=0;used={};current=null;helpUsed={"5050":false,"poll":false,"change":false};home.classList.add('hidden');result.classList.add('hidden');play.classList.remove('hidden');bindHelp();if(window.LHGameTheme&&window.LHGameTheme.intro)window.LHGameTheme.intro();render()}
function getSelectedPlayerName(){var id=student?student.value:'';var list=window.GameData&&window.GameData.getStudents?window.GameData.getStudents():[];for(var i=0;i<list.length;i++){if(studentId(list[i])===id)return studentName(list[i])}var opt=student&&student.options?student.options[student.selectedIndex]:null;return opt?String(opt.textContent||'').trim():(id||'Học sinh')}
function escapeHtml(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function resultPlayerName(x){var direct=x&&(x.studentName||x.playerName||x.name);if(direct)return String(direct);var id=x&&x.studentId?String(x.studentId):'';var list=window.GameData&&window.GameData.getStudents?window.GameData.getStudents():[];for(var i=0;i<list.length;i++){if(studentId(list[i])===id)return studentName(list[i])}return id||'Học sinh'}
function finish(){clearQuestionTimers();play.classList.add('hidden');result.classList.remove('hidden');if(window.LHGameTheme&&window.LHGameTheme.victory)window.LHGameTheme.victory();var playerName=getSelectedPlayerName();$('resultText').innerHTML='<p class="result-good">'+score+' điểm</p><p><b>Người chơi:</b> '+escapeHtml(playerName)+'</p><p>Đã hoàn thành '+idx+'/15 câu.</p>';if(window.GameData&&window.GameData.saveResult)window.GameData.saveResult({id:'GAME_'+Date.now(),studentId:student.value,studentName:playerName,subject:mode.value==='mixed'?'mixed':subject.value,chapter:mode.value==='mixed'?'ALL':chapter.value,level:level.value,totalQuestions:idx,score:score,date:new Date().toISOString()})}
function view(title,body){clearQuestionTimers();home.classList.add('hidden');play.classList.add('hidden');result.classList.add('hidden');document.querySelectorAll('.game-view').forEach(function(x){x.remove()});var v=document.createElement('section');v.className='panel game-view';v.innerHTML='<h2>'+title+'</h2>'+body+'<p><button type="button" data-back>← Trang chủ</button></p>';v.querySelector('[data-back]').onclick=showHome;document.querySelector('.app').appendChild(v)}
function leaderboard(){var r=window.GameData&&window.GameData.getResults?window.GameData.getResults().slice():[];r.sort(function(a,b){var ds=Number(b.score||0)-Number(a.score||0);if(ds)return ds;return String(a.date||'').localeCompare(String(b.date||''))});view('🏆 Bảng xếp hạng',r.length?'<div class="table-wrap"><table class="ranking-table"><thead><tr><th>Hạng</th><th>Tên người chơi</th><th>Điểm</th><th>Kết quả</th></tr></thead><tbody>'+r.slice(0,20).map(function(x,i){return '<tr><td><b>🏆 Hạng '+(i+1)+'</b></td><td>'+escapeHtml(resultPlayerName(x))+'</td><td><b>'+Number(x.score||0)+'</b> điểm</td><td>Hoàn thành '+Number(x.totalQuestions||0)+'/15 câu</td></tr>'}).join('')+'</tbody></table></div>':'<p>Chưa có kết quả.</p>')}
function results(){var r=window.GameData&&window.GameData.getResults?window.GameData.getResults().slice():[];view('📈 Kết quả học tập',r.length?'<div class="table-wrap"><table><thead><tr><th>Người chơi</th><th>Điểm</th><th>Kết quả</th></tr></thead><tbody>'+r.reverse().map(function(x){return '<tr><td>'+escapeHtml(resultPlayerName(x))+'</td><td>'+Number(x.score||0)+' điểm</td><td>Hoàn thành '+Number(x.totalQuestions||0)+'/15 câu</td></tr>'}).join('')+'</tbody></table></div>':'<p>Chưa có kết quả.</p>')}
function bank(){view('🗂️ Ngân hàng câu hỏi','<p>Đang có <b>'+questions.length+'</b> câu hỏi từ BO_CAU_HOI.</p>')}
function admin(){view('⚙️ Quản trị giáo viên','<p>Hệ thống ngân hàng câu hỏi đang dùng BO_CAU_HOI làm nguồn dữ liệu.</p>')}
function bindMenuActions(){if(window.__LH_GAME_MENU_ACTIONS_10__)return;window.__LH_GAME_MENU_ACTIONS_10__=true;document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-action]');if(!b)return;var a=b.getAttribute('data-action');if(a==='leaderboard'){e.preventDefault();leaderboard();return}if(a==='results'){e.preventDefault();results();return}if(a==='bank'){e.preventDefault();bank();return}if(a==='admin'){e.preventDefault();admin();return}if(a==='home'){e.preventDefault();showHome();return}},false)}
function init(){home=$('home');play=$('play');result=$('result');student=$('student');subject=$('subject');chapter=$('chapter');level=$('level');mode=$('gameMode');nextDisplay=$('nextPlayerDisplay');try{playersUsed=JSON.parse(localStorage.getItem('trieu_phu_hoc_duong_players_used')||'{}')||{}}catch(e){playersUsed={}}fillStudents(window.GameData&&window.GameData.getStudents?window.GameData.getStudents():[]);document.querySelector('[data-action="start"]').onclick=start;bindMenuActions();var np=$('nextPlayerButton');if(np){np.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();nextPlayer()},false);np.addEventListener('touchend',function(e){e.preventDefault();e.stopPropagation();nextPlayer()},false)}subject.onchange=chapters;mode.onchange=chapters;window.initQuestionFilters=chapters;syncQuestions();bindHelp();setTimeout(syncQuestions,500);setTimeout(syncQuestions,1500);setTimeout(syncQuestions,3000);window.addEventListener('questionBankReady',function(){syncQuestions();bindHelp()});window.addEventListener('gameRosterReady',function(e){fillStudents(e.detail&&e.detail.count?window.GameData.getStudents():[])});loadPlayers()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
