/* TRIỆU PHÚ HỌC ĐƯỜNG — GAME ENGINE 4.2 STABLE */
(function(){'use strict';
var questions=[],idx=0,score=0,used={},current=null,locked=false,answerTimer=null;
var home,play,result,student,subject,chapter,level,mode,nextDisplay;
var playersUsed={};
var helpUsed={"5050":false,"poll":false,"change":false};
function $(id){return document.getElementById(id)}
function normalize(v){return String(v==null?'':v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[\s_\-&/]+/g,'').toUpperCase()}
function sub(v){var s=normalize(v);if(['TOAN','MATH','MATHEMATICS'].indexOf(s)>=0)return'math';if(['TV','TIENGVIET','VIETNAMESE'].indexOf(s)>=0)return'vietnamese';if(['KH','KHOAHOC','SCIENCE'].indexOf(s)>=0)return'science';if(['LSDL','LSDIALI','LICHSUDIALI','LICHSUVADIALI','LICHSUVAĐIALI','HISTORY','HISTORYGEOGRAPHY','HISTORYANDGEOGRAPHY'].indexOf(s)>=0)return'history';return s.toLowerCase()}
function chapterValue(q){if(!q)return'';var v=q.chapter!=null?q.chapter:(q.Chuong!=null?q.Chuong:(q.topic!=null?q.topic:''));return String(v==null?'':v).normalize('NFC').replace(/[\uFEFF]/g,'').trim().replace(/\s+/g,' ')}
function chapterKey(v){return String(v==null?'':v).normalize('NFC').replace(/[\uFEFF]/g,'').trim().replace(/\s+/g,' ')}
function loadPlayers(){var list=window.GameData&&window.GameData.getStudents?window.GameData.getStudents():[];if(list.length){fillStudents(list);return Promise.resolve(list)}if(window.GameData&&window.GameData.loadStudents)return Promise.resolve(window.GameData.loadStudents()).then(function(){var a=window.GameData.getStudents();fillStudents(a);return a});return Promise.resolve([])}
function fillStudents(list){if(!student)return;student.innerHTML='';(list||[]).forEach(function(s){var id=String(s.id||s.studentCode||s.studentId||s.name||s.studentName||'');if(!id)return;var o=document.createElement('option');o.value=id;o.textContent=s.name||s.studentName||id;student.appendChild(o)});if(!student.options.length){var o=document.createElement('option');o.value='guest';o.textContent='Học sinh chưa đồng bộ — chơi thử';student.appendChild(o)}}
function nextPlayer(){loadPlayers().then(function(list){if(!list.length){alert('Chưa có danh sách học sinh để chọn.');return}var available=list.filter(function(s){var id=String(s.id||s.studentCode||s.studentId||s.name||s.studentName||'');return id&&!playersUsed[id]});if(!available.length){if(!confirm('🎉 Đã chọn hết học sinh trong vòng này. Bắt đầu vòng mới?'))return;playersUsed={};try{localStorage.removeItem('trieu_phu_hoc_duong_players_used')}catch(e){}available=list.slice()}var s=available[Math.floor(Math.random()*available.length)],id=String(s.id||s.studentCode||s.studentId||s.name||s.studentName||'');playersUsed[id]=true;try{localStorage.setItem('trieu_phu_hoc_duong_players_used',JSON.stringify(playersUsed))}catch(e){}if(student)student.value=id;if(nextDisplay)nextDisplay.textContent='🎉 Người chơi tiếp theo: '+(s.name||s.studentName||id)})}
function chapters(){if(!chapter)return;var m=mode?mode.value:'bySubject';if(m==='mixed'){chapter.disabled=true;chapter.innerHTML='<option value="">🌐 Tổng hợp 4 môn — không chia chương</option>';return}var target=sub(subject?subject.value:'math'),set={};questions.forEach(function(q){if(sub(q.subject)!==target)return;var c=chapterValue(q);if(c)set[c]=1});var keys=Object.keys(set).sort(function(a,b){return a.localeCompare(b,'vi',{numeric:true,sensitivity:'base'})});chapter.innerHTML='';if(!keys.length){chapter.disabled=true;chapter.innerHTML='<option value="">⚠️ Chưa có chương cho môn này</option>';return}var first=document.createElement('option');first.value='';first.textContent='📚 Chọn chương';chapter.appendChild(first);keys.forEach(function(c){var o=document.createElement('option');o.value=c;o.textContent='📘 '+c;chapter.appendChild(o)});chapter.disabled=false}
function syncQuestions(){questions=Array.isArray(window.GAME_QUESTIONS)?window.GAME_QUESTIONS:[];chapters()}
function pool(){var m=mode?mode.value:'bySubject',s=sub(subject?subject.value:'math'),c=chapterKey(chapter?chapter.value:''),lv=level?level.value:'ALL';return questions.filter(function(q){if(q.status&&String(q.status).toUpperCase()!=='ACTIVE')return false;if(m!=='mixed'&&sub(q.subject)!==s)return false;if(m!=='mixed'&&c&&chapterKey(chapterValue(q))!==c)return false;if(lv!=='ALL'&&q.level!==lv)return false;return true})}
function showHome(){home.classList.remove('hidden');play.classList.add('hidden');result.classList.add('hidden');document.querySelectorAll('.game-view').forEach(function(x){x.remove()});syncQuestions()}
function renderQuestion(q){locked=false;clearTimeout(answerTimer);current=q;$('counter').textContent='Câu '+(idx+1)+'/15';$('score').textContent=score+' điểm';$('question').textContent=q.question;var box=$('answers');box.innerHTML='';(q.options||[]).forEach(function(t,i){var b=document.createElement('button');b.type='button';b.textContent=String.fromCharCode(65+i)+'. '+t;b.dataset.i=i;b.onclick=function(){answer(i)};box.appendChild(b)});$('explanation').textContent='';updateHelpButtons()}
function render(){var list=pool().filter(function(q){return !used[q.id]});if(!list.length)list=pool();if(!list.length){$('question').textContent='❌ Không có câu hỏi phù hợp với lựa chọn.';$('answers').innerHTML='';return}current=list[Math.floor(Math.random()*list.length)];used[current.id]=true;renderQuestion(current)}
function answer(i){if(locked||!current)return;locked=true;var buttons=document.querySelectorAll('#answers button');buttons.forEach(function(b){b.disabled=true});var ok=i===Number(current.correctAnswer);if(ok){score+=Number(current.points||1)*10;buttons[i].style.outline='3px solid #16a34a'}else{buttons[i].style.outline='3px solid #dc2626';if(buttons[current.correctAnswer])buttons[current.correctAnswer].style.outline='3px solid #16a34a'}var text=(ok?'✅ Chính xác! ':'❌ Chưa chính xác. ')+(current.explanation||'');$('explanation').textContent=text+'  ⏱️ Chuyển câu sau 10 giây…';var left=10;answerTimer=setInterval(function(){left--;if(left>0)$('explanation').textContent=text+'  ⏱️ Chuyển câu sau '+left+' giây…'},1000);setTimeout(function(){clearInterval(answerTimer);idx++;if(idx>=15)finish();else render()},10000)}
function updateHelpButtons(){document.querySelectorAll('[data-help]').forEach(function(b){var k=b.getAttribute('data-help');b.disabled=!!helpUsed[k]})}
function help5050(){if(helpUsed['5050']||locked||!current)return;helpUsed['5050']=true;var buttons=[].slice.call(document.querySelectorAll('#answers button'));var wrong=buttons.filter(function(b){return Number(b.dataset.i)!==Number(current.correctAnswer)&&!b.disabled});wrong.slice(0,2).forEach(function(b){b.disabled=true;b.style.opacity='.35';b.style.textDecoration='line-through'});$('explanation').textContent='💡 50:50: Đã loại 2 đáp án sai.';updateHelpButtons();if(window.LHGameTheme)window.LHGameTheme.help('5050')}
function poll(){if(helpUsed.poll||locked||!current)return;helpUsed.poll=true;var c=Number(current.correctAnswer),v=[0,0,0,0],r=100;var wrong=[0,1,2,3].filter(function(i){return i!==c});wrong.forEach(function(i,n){var max=Math.max(1,Math.floor(r*(n===wrong.length-1?1:.55)));var value=n===wrong.length-1?Math.floor(r*.35):Math.floor(Math.random()*max);v[i]=value;r-=value});v[c]=r;var total=v.reduce(function(a,b){return a+b},0)||100;v=v.map(function(x){return Math.round(x*100/total)});v[c]+=100-v.reduce(function(a,b){return a+b},0);$('explanation').innerHTML='👥 <b>Hỏi cả lớp:</b> A '+v[0]+'% • B '+v[1]+'% • C '+v[2]+'% • D '+v[3]+'%';updateHelpButtons();if(window.LHGameTheme)window.LHGameTheme.help('poll')}
function changeQuestion(){if(helpUsed.change||locked||!current)return;var candidates=pool().filter(function(q){return q.id!==current.id&&!used[q.id]});if(!candidates.length){$('explanation').textContent='⚠️ Không còn câu hỏi khác phù hợp.';return}helpUsed.change=true;var n=candidates[Math.floor(Math.random()*candidates.length)];used[n.id]=true;renderQuestion(n);$('explanation').textContent='🔄 Đã đổi sang câu hỏi mới.';updateHelpButtons();if(window.LHGameTheme)window.LHGameTheme.change()}
function bindHelp(){document.querySelectorAll('[data-help]').forEach(function(b){b.onclick=function(){var k=b.getAttribute('data-help');if(k==='5050')help5050();else if(k==='poll')poll();else if(k==='change')changeQuestion()}});updateHelpButtons()}
function start(){syncQuestions();if(window.QuestionBank&&!window.QuestionBank.ready){if(window.QuestionBank.load)window.QuestionBank.load();setTimeout(start,700);return}if(!questions.length){alert('Ngân hàng câu hỏi chưa tải xong.');return}idx=0;score=0;used={};current=null;helpUsed={"5050":false,"poll":false,"change":false};home.classList.add('hidden');result.classList.add('hidden');play.classList.remove('hidden');bindHelp();render()}
function finish(){play.classList.add('hidden');result.classList.remove('hidden');$('resultText').innerHTML='<p class="result-good">'+score+' điểm</p><p>Đã hoàn thành '+idx+'/15 câu.</p>';if(window.GameData&&window.GameData.saveResult)window.GameData.saveResult({id:'GAME_'+Date.now(),studentId:student.value,subject:mode.value==='mixed'?'mixed':subject.value,chapter:mode.value==='mixed'?'ALL':chapter.value,level:level.value,totalQuestions:idx,score:score,date:new Date().toISOString()})}
function view(title,body){home.classList.add('hidden');play.classList.add('hidden');result.classList.add('hidden');document.querySelectorAll('.game-view').forEach(function(x){x.remove()});var v=document.createElement('section');v.className='panel game-view';v.innerHTML='<h2>'+title+'</h2>'+body+'<p><button type="button" data-back>← Trang chủ</button></p>';v.querySelector('[data-back]').onclick=showHome;document.querySelector('.app').appendChild(v)}
function leaderboard(){var r=window.GameData&&window.GameData.getResults?window.GameData.getResults():[];r.sort(function(a,b){return Number(b.score||0)-Number(a.score||0)});view('🏆 Bảng xếp hạng',r.length?r.slice(0,20).map(function(x,i){return '<p><b>'+(i+1)+'. '+(x.studentId||'Học sinh')+'</b> — '+(x.score||0)+' điểm</p>'}).join(''):'<p>Chưa có kết quả.</p>')}
function results(){var r=window.GameData&&window.GameData.getResults?window.GameData.getResults():[];view('📈 Kết quả học tập',r.length?r.slice().reverse().map(function(x){return '<p><b>'+(x.studentId||'Học sinh')+'</b> — '+(x.score||0)+' điểm</p>'}).join(''):'<p>Chưa có kết quả.</p>')}
function bank(){view('🗂️ Ngân hàng câu hỏi','<p>Đang có <b>'+questions.length+'</b> câu hỏi từ BO_CAU_HOI.</p>')}
function admin(){view('⚙️ Quản trị giáo viên','<p>Hệ thống ngân hàng câu hỏi đang dùng BO_CAU_HOI làm nguồn dữ liệu.</p>')}
function init(){home=$('home');play=$('play');result=$('result');student=$('student');subject=$('subject');chapter=$('chapter');level=$('level');mode=$('gameMode');nextDisplay=$('nextPlayerDisplay');try{playersUsed=JSON.parse(localStorage.getItem('trieu_phu_hoc_duong_players_used')||'{}')||{}}catch(e){playersUsed={}}fillStudents(window.GameData&&window.GameData.getStudents?window.GameData.getStudents():[]);document.querySelector('[data-action="start"]').onclick=start;document.querySelector('[data-action="leaderboard"]').onclick=leaderboard;document.querySelector('[data-action="results"]').onclick=results;document.querySelector('[data-action="bank"]').onclick=bank;document.querySelector('[data-action="admin"]').onclick=admin;document.querySelector('[data-action="home"]').onclick=showHome;document.querySelector('#nextPlayerButton').onclick=nextPlayer;subject.onchange=chapters;mode.onchange=chapters;window.initQuestionFilters=chapters;syncQuestions();bindHelp();setTimeout(syncQuestions,500);setTimeout(syncQuestions,1500);setTimeout(syncQuestions,3000);window.addEventListener('questionBankReady',function(){syncQuestions();bindHelp()});loadPlayers()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();