/* TRIỆU PHÚ HỌC ĐƯỜNG — HELP CONTROLS FIX */
(function(){'use strict';
function $(id){return document.getElementById(id)}
function currentQuestion(){var t=$('question')&&$('question').textContent||'';var qs=window.GAME_QUESTIONS||[];return qs.find(function(q){return String(q.question||'')===t})||null}
function help5050(){var q=currentQuestion();if(!q)return;var bs=[].slice.call(document.querySelectorAll('#answers button'));var wrong=bs.filter(function(b){return Number(b.dataset.i)!==Number(q.correctAnswer)&&!b.disabled});for(var i=wrong.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),x=wrong[i];wrong[i]=wrong[j];wrong[j]=x}wrong.slice(0,2).forEach(function(b){b.disabled=true;b.style.opacity='.35';b.style.textDecoration='line-through'});$('explanation').textContent='💡 50:50: Đã loại 2 đáp án sai.';if(window.LHGameTheme)window.LHGameTheme.help('5050')}
function poll(){var q=currentQuestion();if(!q)return;var c=Number(q.correctAnswer),v=[0,0,0,0],r=100;for(var i=0;i<4;i++){if(i===c)continue;var n=Math.floor(Math.random()*Math.max(1,r*.45));v[i]=n;r-=n}v[c]=r;$('explanation').innerHTML='👥 <b>Hỏi cả lớp:</b> A '+v[0]+'% • B '+v[1]+'% • C '+v[2]+'% • D '+v[3]+'%';if(window.LHGameTheme)window.LHGameTheme.help('poll')}
function change(){var q=currentQuestion(),qs=window.GAME_QUESTIONS||[];if(!q)return;var candidates=qs.filter(function(x){return String(x.question||'')!==String(q.question||'')&&Number(x.correctAnswer)===Number(q.correctAnswer)});if(!candidates.length)candidates=qs.filter(function(x){return String(x.question||'')!==String(q.question||'')});if(!candidates.length)return;var n=candidates[Math.floor(Math.random()*candidates.length)],box=$('answers');$('question').textContent=n.question;box.innerHTML='';(n.options||[]).forEach(function(t,i){var b=document.createElement('button');b.type='button';b.dataset.i=i;b.textContent=String.fromCharCode(65+i)+'. '+t;b.onclick=function(){var old=document.querySelector('#answers button');var ev=new MouseEvent('click',{bubbles:true});if(old){};document.querySelectorAll('#answers button').forEach(function(x){x.onclick=null});var oldButtons=box.querySelectorAll('button');oldButtons.forEach(function(x){x.onclick=function(){var original=Number(x.dataset.i);var fake=Number(n.correctAnswer)===original;oldButtons.forEach(function(y){y.disabled=true});x.style.outline=fake?'3px solid #16a34a':'3px solid #dc2626';if(oldButtons[n.correctAnswer])oldButtons[n.correctAnswer].style.outline='3px solid #16a34a';$('explanation').textContent=(fake?'✅ Chính xác! ':'❌ Chưa chính xác. ')+'⏱️ Chuyển câu sau 10 giây…';setTimeout(function(){location.reload()},10000)}}});};box.querySelectorAll('button').forEach(function(x){x.onclick=function(){var original=Number(x.dataset.i),fake=Number(n.correctAnswer)===original;box.querySelectorAll('button').forEach(function(y){y.disabled=true});x.style.outline=fake?'3px solid #16a34a':'3px solid #dc2626';if(box.querySelectorAll('button')[n.correctAnswer])box.querySelectorAll('button')[n.correctAnswer].style.outline='3px solid #16a34a';$('explanation').textContent=(fake?'✅ Chính xác! ':'❌ Chưa chính xác. ')+'⏱️ Chuyển câu sau 10 giây…';setTimeout(function(){location.reload()},10000)}});$('explanation').textContent='🔄 Đã đổi câu hỏi.';if(window.LHGameTheme)window.LHGameTheme.change()}
function bind(){document.querySelectorAll('[data-help]').forEach(function(b){b.onclick=function(){var k=b.getAttribute('data-help');if(k==='5050')help5050();else if(k==='poll')poll();else if(k==='change')change()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(bind,300)});else setTimeout(bind,300);window.addEventListener('questionBankReady',function(){setTimeout(bind,100)})
})();