/* TRIỆU PHÚ HỌC ĐƯỜNG — QUESTION BANK 6.0
   Nguồn duy nhất: Google Sheets / BO_CAU_HOI.
   Ưu tiên đọc toàn bộ bảng một lần để tránh 47+ request nhỏ.
   Nếu request lớn thất bại/chậm, tự động fallback sang lô 300 dòng.
   Không dùng Học kỳ hoặc Trạng thái để loại câu hỏi.
*/
(function(){'use strict';
if(window.__LH_QB_60__) return; window.__LH_QB_60__=true;
var SHEET_ID='1n8ES33AkncKR6FzK0VODMgzDbycoyA_GsPIRuj7LEDM',SHEET_NAME='BO_CAU_HOI';
var BASE='https://docs.google.com/spreadsheets/d/'+SHEET_ID+'/gviz/tq';
var CHUNK=300,FULL_TIMEOUT=45000,CHUNK_TIMEOUT=30000,MAX_CHUNKS=30;
window.QuestionBank={ready:false,count:0,rawRows:0,rejectedRows:0,duplicates:0,chunks:0,error:null,url:BASE,version:'6.0'};
function clean(v){return v==null?'':String(v).replace(/^\uFEFF/,'').trim()}
function norm(v){return clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/Đ/g,'D').replace(/đ/g,'d').replace(/[\s_\-&/.:]+/g,'').toUpperCase()}
function subject(v,id){var s=norm(v),r=String(id==null?'':id).trim().toUpperCase();
 if(/^(TOAN|MATH|MATHEMATICS|MATHEMATICS5)$/.test(s)||/(^|[-_])(TOAN|MATH)([-_]|$)/.test(r)||r.indexOf('TOAN')>=0)return'math';
 if(/^(TV|TIENGVIET|VIETNAMESE|VIETNAMESE5)$/.test(s)||/(^|[-_])(TV|TIENGVIET|VIETNAMESE)([-_]|$)/.test(r)||r.indexOf('TIENGVIET')>=0||r.indexOf('VIETNAMESE')>=0)return'vietnamese';
 if(/^(KH|KHOAHOC|KHOAHOC5|SCIENCE|NATURALSCIENCE|NATURALSCIENCE5)$/.test(s)||/(^|[-_])(KH|KHOAHOC|SCIENCE)([-_]|$)/.test(r)||r.indexOf('KHOA_HOC')>=0||r.indexOf('KHOA-HOC')>=0||r.indexOf('KHOAHOC')>=0)return'science';
 if(/^(LSDL|LSDIALI|LSDIALI5|LICHSUDIALI|LICHSUVADIALI|HISTORY|HISTORYGEOGRAPHY|HISTORYANDGEOGRAPHY)$/.test(s)||/(^|[-_])LS[-_]?DL([-_]|$)/.test(r)||/(^|[-_])LSDIALI([-_]|$)/.test(r)||r.indexOf('LSDIALI')>=0||r.indexOf('LICHSUDIALI')>=0||r.indexOf('HISTORYGEOGRAPHY')>=0)return'history';return''}
function topicCode(id,chapter){var r=String(id==null?'':id).trim().toUpperCase(),m=r.match(/(?:^|[-_])C(\d{1,2})(?:[-_]|$)/);if(m)return'C'+String(Number(m[1])).padStart(2,'0');var t=norm(chapter).match(/CHUDE(\d{1,2})/);return t?'C'+String(Number(t[1])).padStart(2,'0'):''}
function num(v,d){var n=Number(String(v==null?'').replace(',','.'));return Number.isFinite(n)?n:d}
function answerIndex(v){var s=norm(v);if(s==='A'||s==='1')return 0;if(s==='B'||s==='2')return 1;if(s==='C'||s==='3')return 2;if(s==='D'||s==='4')return 3;var n=Number(s);return Number.isFinite(n)&&n>=0&&n<=3?n:0}
function cell(c,i){var x=c&&c[i];return x?clean(x.v!=null?x.v:x.f):''}
function parseRows(data,offset){if(!data||!data.table)throw new Error('Google Sheets không trả về bảng BO_CAU_HOI');var rows=data.table.rows||[],list=[],rejected=0;rows.forEach(function(r,ri){var c=r.c||[],id=cell(c,1),mon=cell(c,2),hocKy=cell(c,3),chuong=cell(c,4),bo=cell(c,5),muc=cell(c,6),nhom=cell(c,7),question=cell(c,8),A=cell(c,9),B=cell(c,10),C=cell(c,11),D=cell(c,12),answer=cell(c,13),explain=cell(c,14),points=cell(c,15),time=cell(c,16),status=cell(c,17);if(!id||!question||!A||!B||!C||!D){rejected++;return}var sk=subject(mon,id),tc=topicCode(id,chuong),ch=chuong||('Chủ đề '+Number(tc.replace(/\D/g,'')||0));list.push({id:id,subject:sk,subjectKey:sk,Mon:mon,semester:hocKy,topicCode:tc,topicKey:sk+'|'+tc,chapter:ch,Chuong:ch,topic:ch,topicName:ch,set:bo,level:muc||'M1',group:nhom,question:question,options:[A,B,C,D],correctAnswer:answerIndex(answer),explanation:explain,points:num(points,1),time:num(time,30),status:status||'ACTIVE',stt:cell(c,0),_row:offset+ri+2})});return{rows:rows.length,list:list,rejected:rejected}}
function setStatus(t,state){var e=document.getElementById('questionBankStatus');if(e){e.textContent=t;e.dataset.state=state||'loading'}}
function finish(all,rejected,rawRows,chunks){var seen={},unique=[],dupes=0;all.forEach(function(q){var k=String(q.id||'').trim();if(!k||seen[k]){if(k)dupes++;return}seen[k]=1;unique.push(q)});var old=Array.isArray(window.GAME_QUESTIONS)?window.GAME_QUESTIONS:[];old.splice(0,old.length);Array.prototype.push.apply(old,unique);window.GAME_QUESTIONS=old;window.QuestionBank.ready=true;window.QuestionBank.count=unique.length;window.QuestionBank.rawRows=rawRows;window.QuestionBank.rejectedRows=rejected;window.QuestionBank.duplicates=dupes;window.QuestionBank.chunks=chunks;window.QuestionBank.error=null;setStatus('☁️ BO_CAU_HOI: '+unique.length+' câu • đọc '+rawRows+' dòng • sẵn sàng Môn/Chủ đề','ok');try{window.dispatchEvent(new CustomEvent('questionBankReady',{detail:{count:unique.length,rawRows:rawRows,rejectedRows:rejected,duplicates:dupes,chunks:chunks}}))}catch(e){}if(typeof window.initQuestionFilters==='function')try{window.initQuestionFilters()}catch(e){}}
function fail(e){window.QuestionBank.ready=false;window.QuestionBank.error=e;setStatus('❌ '+(e&&e.message?e.message:'Không tải được BO_CAU_HOI'),'error')}
function jsonp(url,timeout){return new Promise(function(resolve,reject){var cb='__LH_QB_'+Date.now()+'_'+Math.random().toString(36).slice(2);var s=document.createElement('script'),done=false,t=setTimeout(function(){if(done)return;done=true;delete window[cb];if(s.parentNode)s.parentNode.removeChild(s);reject(new Error('Google Sheets phản hồi quá chậm'))},timeout);window[cb]=function(data){if(done)return;done=true;clearTimeout(t);delete window[cb];if(s.parentNode)s.parentNode.removeChild(s);resolve(data)};s.onerror=function(){if(done)return;done=true;clearTimeout(t);delete window[cb];if(s.parentNode)s.parentNode.removeChild(s);reject(new Error('Không truy cập được Google Sheets'))};s.src=url+'&tqx='+encodeURIComponent('out:json;responseHandler:'+cb)+'&t='+Date.now();s.async=true;document.head.appendChild(s)})}
async function tryFull(){var tq='select * where B is not null';var url=BASE+'?sheet='+encodeURIComponent(SHEET_NAME)+'&headers=1&tq='+encodeURIComponent(tq);setStatus('☁️ Đang tải toàn bộ BO_CAU_HOI…', 'loading');var data=await jsonp(url,FULL_TIMEOUT);return parseRows(data,0)}
async function tryChunks(){var all=[],offset=0,totalRejected=0,chunks=0;for(var i=0;i<MAX_CHUNKS;i++){var tq='select * where B is not null limit '+CHUNK+' offset '+offset;var url=BASE+'?sheet='+encodeURIComponent(SHEET_NAME)+'&headers=1&tq='+encodeURIComponent(tq);setStatus('☁️ Đang tải BO_CAU_HOI… '+offset+'+','loading');var parsed=await jsonp(url,CHUNK_TIMEOUT);var p=parseRows(parsed,offset);if(!p.rows)break;all=all.concat(p.list);totalRejected+=p.rejected;chunks++;offset+=p.rows;if(p.rows<CHUNK)break}return{rows:offset,list:all,rejected:totalRejected,chunks:chunks}}
async function load(){if(window.QuestionBank.ready||window.__LH_QB_LOADING__)return;window.__LH_QB_LOADING__=true;window.QuestionBank.ready=false;window.QuestionBank.error=null;try{var full;try{full=await tryFull();if(!full.rows)throw new Error('Bảng rỗng');finish(full.list,full.rejected,full.rows,1)}catch(e){console.warn('[QB 6.0] Full-load fallback:',e);var many=await tryChunks();if(!many.list.length)throw new Error('Không đọc được dữ liệu BO_CAU_HOI');finish(many.list,many.rejected,many.rows,many.chunks)}}catch(e){fail(e)}finally{window.__LH_QB_LOADING__=false}}
window.QuestionBank.load=load;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load();
})();