/* TRIỆU PHÚ HỌC ĐƯỜNG — TOPIC ROUTER 2.0
   SINGLE SOURCE: dựng danh sách Chủ đề từ GAME_QUESTIONS.
   KHÔNG sửa GAME_QUESTIONS.
   Khóa nội bộ = Môn + Cxx lấy từ ID.
   Tên hiển thị = Chuong gốc của BO_CAU_HOI.
*/
(function(){
'use strict';
if(window.__LH_TOPIC_ROUTER_20__)return;
window.__LH_TOPIC_ROUTER_20__=true;
function text(v){return String(v==null?'':v).replace(/^\uFEFF/,'').trim().replace(/\s+/g,' ')}
function norm(v){return text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/Đ/g,'D').replace(/đ/g,'d').replace(/[\s_\-&/.:]+/g,'').toUpperCase()}
function subject(mon,id){var s=norm(mon),r=String(id==null?'':id).trim().toUpperCase();if(/^(TOAN|MATH|MATHEMATICS)$/.test(s)||/(^|[-_])TOAN([_-]|$)/.test(r)||r.indexOf('MATH')>=0)return'math';if(/^(TV|TIENGVIET|VIETNAMESE)$/.test(s)||/(^|[-_])TV([_-]|$)/.test(r)||r.indexOf('TIENGVIET')>=0)return'vietnamese';if(/^(KH|KHOAHOC|KHOAHOC5|SCIENCE|NATURALSCIENCE)$/.test(s)||/(^|[-_])KH([_-]|$)/.test(r)||r.indexOf('KHOA_HOC')>=0||r.indexOf('KHOA-HOC')>=0||r.indexOf('KHOAHOC')>=0)return'science';if(/^(LSDL|LSDIALI|LSDIALI5|LICHSUDIALI|LICHSUVADIALI|HISTORY|HISTORYGEOGRAPHY|HISTORYANDGEOGRAPHY)$/.test(s)||/(^|[-_])LS[_-]?DL([_-]|$)/.test(r)||r.indexOf('LSDIALI')>=0||r.indexOf('LICHSUDIALI')>=0)return'history';return s.toLowerCase()}
function topicCode(id,topic){var r=String(id==null?'':id).trim().toUpperCase(),m=r.match(/(?:^|[-_])C(\d{1,2})(?:[-_]|$)/);if(m)return'C'+String(Number(m[1])).padStart(2,'0');var t=text(topic).normalize('NFC').match(/(?:^|\s)Ch(?:u|ủ)\s*đề\s*([0-9]{1,2})/i);return t?'C'+String(Number(t[1])).padStart(2,'0'):''}
function topicName(q,code){var a=[q&&q.Chuong,q&&q.topicName,q&&q.topic,q&&q.chapter,q&&q.ChuDe,q&&q.chude];for(var i=0;i<a.length;i++){var v=text(a[i]);if(v&&!/^C\d{2}$/.test(v))return v}return code?'Chủ đề '+Number(code.slice(1)):'Chủ đề chưa xác định'}
function render(){var sel=document.getElementById('chapter'),subSel=document.getElementById('subject'),mode=document.getElementById('gameMode');if(!sel||!subSel)return;if(mode&&mode.value==='mixed'){sel.innerHTML='<option value="">🌐 Tổng hợp 4 môn — không chia chủ đề</option>';sel.disabled=true;return}var qs=Array.isArray(window.GAME_QUESTIONS)?window.GAME_QUESTIONS:[];if(!qs.length){sel.innerHTML='<option value="">⏳ Đang tải chủ đề...</option>';sel.disabled=true;return}var target=subject(subSel.value,''),map={};qs.forEach(function(q){if(!q)return;var sid=q.id||q.ID||'';if(subject(q.Mon||q.mon,sid)!==target)return;var c=topicCode(sid,q.Chuong||q.chapter||q.topic||q.topicName||'');if(!c)return;var name=topicName(q,c);if(!map[c])map[c]={name:name,count:0};map[c].count++;if(name.length>map[c].name.length)map[c].name=name});var keys=Object.keys(map).sort(function(a,b){return Number(a.slice(1))-Number(b.slice(1))}),old=String(sel.value||''),sig=target+'|'+keys.map(function(k){return k+'='+map[k].name+'#'+map[k].count}).join('|');if(sel.dataset.lh20===sig&&sel.options.length)return;sel.dataset.lh20=sig;sel.innerHTML='';if(!keys.length){sel.disabled=true;sel.innerHTML='<option value="">⚠️ Chưa có chủ đề cho môn này</option>';return}var first=document.createElement('option');first.value='';first.textContent='📚 Chọn chủ đề / chương';sel.appendChild(first);keys.forEach(function(code){var o=document.createElement('option');o.value=map[code].name;o.textContent='📘 '+map[code].name+' ('+map[code].count+' câu)';o.dataset.topicCode=code;o.dataset.questionCount=String(map[code].count);sel.appendChild(o)});sel.disabled=false;if(old&&Array.prototype.some.call(sel.options,function(o){return o.value===old}))sel.value=old}
window.LHTopicRouter={render:render,subject:subject,topicCode:topicCode,refresh:render};
function hook(){var s=document.getElementById('subject'),m=document.getElementById('gameMode');if(s)s.addEventListener('change',render);if(m)m.addEventListener('change',render);window.addEventListener('questionBankReady',function(){setTimeout(render,0)});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook,{once:true});else hook();
})();
