/* HỌC TẬP — GIAI ĐOẠN 1 — MASTER
 * CHỈ MODULE HỌC TẬP — KHÔNG THAY ĐỔI CSDL / MODULE KHÁC
 */
(function(){
'use strict';
if(window.__LH_LEARNING_MODULE_V6__)return;
window.__LH_LEARNING_MODULE_V6__=true;
const SUBJECTS=['Toán','Tiếng Việt','Khoa học','Lịch sử và Địa lí','Công nghệ','Đạo đức'];
const LEVELS=['Tốt','Đạt','Chưa đạt','H','C'];
const KEY='LH_LEARNING_PHASE1_RECORDS_V5';
const FOCUS={'Toán':'tính toán, suy luận và giải toán','Tiếng Việt':'đọc, viết, nói, nghe và sử dụng tiếng Việt','Khoa học':'quan sát, khám phá và vận dụng kiến thức khoa học','Lịch sử và Địa lí':'tìm hiểu lịch sử, địa lí và quê hương đất nước','Công nghệ':'thực hành, kĩ thuật, sử dụng dụng cụ và an toàn','Đạo đức':'chuẩn mực đạo đức, ứng xử và trách nhiệm'};
const GOOD=['Nắm vững kiến thức về {f} và vận dụng chính xác.','Thực hiện tốt nhiệm vụ học tập liên quan đến {f}.','Biết vận dụng linh hoạt kiến thức {f} vào thực tế.','Có khả năng suy luận và giải thích rõ khi học về {f}.','Chủ động tìm hiểu, khám phá và mở rộng kiến thức về {f}.','Thực hiện nhiệm vụ đầy đủ, chính xác và có trách nhiệm trong {f}.','Có tiến bộ rõ rệt về kĩ năng {f}.','Biết tự kiểm tra, phát hiện và sửa lỗi khi thực hiện {f}.','Trình bày kết quả học tập về {f} rõ ràng, mạch lạc.','Tự tin trao đổi ý kiến và chia sẻ cách làm về {f}.','Biết liên hệ kiến thức {f} với những tình huống gần gũi.','Có khả năng vận dụng kiến thức {f} vào nhiệm vụ mới.','Thực hiện tốt yêu cầu cần đạt về {f}.','Có ý thức tự học và tự điều chỉnh việc học về {f}.','Biết hợp tác với bạn để hoàn thành nhiệm vụ về {f}.','Tiếp thu tốt kiến thức và thực hiện hiệu quả các nhiệm vụ về {f}.','Có tinh thần học tập tích cực và hứng thú với {f}.','Biết lựa chọn cách thực hiện phù hợp khi giải quyết nhiệm vụ về {f}.','Kết quả học tập về {f} ổn định và nổi bật.','Hoàn thành tốt các yêu cầu học tập và vận dụng về {f}.'];
const OK=['Cơ bản nắm được kiến thức về {f} và hoàn thành yêu cầu chính.','Thực hiện được nhiệm vụ về {f} khi có hướng dẫn phù hợp.','Có cố gắng và từng bước tiến bộ trong học tập về {f}.','Hiểu được những nội dung trọng tâm liên quan đến {f}.','Biết vận dụng kiến thức {f} vào tình huống quen thuộc.','Cần rèn thêm tính chính xác và sự chủ động khi học về {f}.','Hoàn thành phần lớn nhiệm vụ học tập liên quan đến {f}.','Có ý thức sửa lỗi sau khi được góp ý về {f}.','Kĩ năng cơ bản về {f} đang đáp ứng yêu cầu.','Cần mạnh dạn hơn khi trình bày ý kiến về {f}.','Biết hợp tác với bạn trong một số nhiệm vụ về {f}.','Có tiến bộ nhưng kết quả học tập về {f} chưa thật ổn định.','Cần duy trì thói quen học tập thường xuyên đối với {f}.','Hoàn thành yêu cầu cơ bản về {f}.','Biết liên hệ kiến thức {f} với tình huống gần gũi.','Có ý thức tự học về {f} nhưng cần duy trì đều hơn.','Cần luyện tập thêm để nâng cao chất lượng nhiệm vụ về {f}.','Thực hiện nhiệm vụ về {f} khá đầy đủ.','Đang hình thành và củng cố kĩ năng vận dụng {f}.','Đáp ứng yêu cầu cần đạt cơ bản về {f}.'];
const NEED=['Chưa nắm chắc một số kiến thức cơ bản về {f}.','Cần được hướng dẫn thêm để hoàn thành nhiệm vụ về {f}.','Kết quả học tập về {f} chưa ổn định.','Cần củng cố kiến thức nền tảng liên quan đến {f}.','Việc vận dụng kiến thức về {f} còn hạn chế.','Cần tăng thời gian luyện tập và ôn tập về {f}.','Chưa hoàn thành đầy đủ nhiệm vụ học tập về {f}.','Cần rèn thói quen học tập thường xuyên hơn đối với {f}.','Cần chủ động hơn trong quá trình học tập về {f}.','Kĩ năng cơ bản liên quan đến {f} chưa vững.','Cần được hỗ trợ khi thực hiện nhiệm vụ mới về {f}.','Chưa duy trì được sự tập trung khi học về {f}.','Cần chú ý hơn khi thực hiện các yêu cầu về {f}.','Chưa biết tự kiểm tra và sửa lỗi thường xuyên trong {f}.','Cần luyện tập thêm để đạt yêu cầu về {f}.','Việc trình bày kết quả liên quan đến {f} còn chưa rõ ràng.','Cần phối hợp tốt hơn khi thực hiện nhiệm vụ về {f}.','Có cố gắng nhưng kết quả về {f} chưa đáp ứng yêu cầu.','Cần kế hoạch hỗ trợ và luyện tập phù hợp về {f}.','Chưa đạt yêu cầu cần đạt liên quan đến {f}.'];
const COMPLETE=['Hoàn thành tốt yêu cầu học tập về {f}.','Hoàn thành đầy đủ nhiệm vụ học tập về {f}.','Hoàn thành yêu cầu cơ bản và biết vận dụng {f}.','Hoàn thành nhiệm vụ đúng yêu cầu về {f}.','Hoàn thành tốt nội dung học tập liên quan đến {f}.','Có ý thức hoàn thành nhiệm vụ về {f}.','Hoàn thành nhiệm vụ và biết sửa lỗi trong {f}.','Hoàn thành yêu cầu, có tiến bộ trong {f}.','Hoàn thành khá tốt các nhiệm vụ về {f}.','Hoàn thành nhiệm vụ với tinh thần trách nhiệm về {f}.','Hoàn thành yêu cầu và biết hợp tác khi học {f}.','Hoàn thành nhiệm vụ, bước đầu vận dụng tốt {f}.','Hoàn thành nội dung trọng tâm của {f}.','Hoàn thành yêu cầu cần đạt về {f}.','Hoàn thành nhiệm vụ tương đối chủ động về {f}.','Hoàn thành các hoạt động học tập liên quan đến {f}.','Hoàn thành nhiệm vụ và có ý thức tự học về {f}.','Hoàn thành yêu cầu với kết quả ổn định về {f}.','Hoàn thành nhiệm vụ, biết liên hệ kiến thức {f}.','Hoàn thành tốt nhiệm vụ được giao về {f}.'];
const NOT_COMPLETE=['Chưa hoàn thành đầy đủ yêu cầu học tập về {f}.','Cần hỗ trợ thêm để hoàn thành nhiệm vụ về {f}.','Cần củng cố kiến thức và kĩ năng về {f}.','Cần luyện tập thường xuyên hơn để hoàn thành {f}.','Chưa hoàn thành một số nhiệm vụ liên quan đến {f}.','Cần chủ động hơn khi thực hiện nhiệm vụ về {f}.','Cần tập trung hơn trong các hoạt động học tập về {f}.','Cần được hướng dẫn thêm khi vận dụng {f}.','Cần rèn kĩ năng cơ bản liên quan đến {f}.','Cần hoàn thiện cách trình bày kết quả về {f}.','Cần tăng cường luyện tập để đáp ứng yêu cầu về {f}.','Cần duy trì việc học thường xuyên đối với {f}.','Cần cố gắng hơn để hoàn thành nhiệm vụ về {f}.','Cần sửa lỗi và hoàn thiện nhiệm vụ về {f}.','Cần hỗ trợ phù hợp để tiến bộ trong {f}.','Chưa hoàn thành yêu cầu cần đạt về {f}.','Cần rèn tính chính xác khi thực hiện {f}.','Cần tích cực hơn trong các hoạt động học tập về {f}.','Cần thêm thời gian để củng cố nội dung về {f}.','Cần tiếp tục cố gắng để hoàn thành tốt {f}.'];
const COMMENTS={};SUBJECTS.forEach(s=>{const f=FOCUS[s],map=a=>a.map(x=>x.replaceAll('{f}',f));COMMENTS[s]={Tốt:map(GOOD),Đạt:map(OK),'Chưa đạt':map(NEED),H:map(COMPLETE),C:map(NOT_COMPLETE)}});
function clean(v){return String(v==null?'':v).trim().replace(/\s+/g,' ')}
function esc(v){return clean(v).replace(/[&<>\'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function uid(){return'HT_'+Date.now()+'_'+Math.random().toString(36).slice(2,9)}
function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
let records=load(),level='';window.learningRecords=records;window.LH_LEARNING_COMMENTS=COMMENTS;
function persist(){try{localStorage.setItem(KEY,JSON.stringify(records))}catch(e){}window.learningRecords=records;if(window.APP_DATA)window.APP_DATA.learning=records;window.dispatchEvent(new CustomEvent('learning-data-updated',{detail:records}))}
function students(){return Array.isArray(window.students)?window.students:Array.isArray(window.GOOGLE_SHEETS_STUDENTS)?window.GOOGLE_SHEETS_STUDENTS:[]}
function addStyle(){if(document.getElementById('lhLearningV6Style'))return;const s=document.createElement('style');s.id='lhLearningV6Style';s.textContent='#lhLearningModal{position:fixed;inset:0;z-index:99999;background:rgba(15,23,42,.55);display:flex;align-items:center;justify-content:center;padding:12px}#lhLearningModal .lh-box{background:#fff;width:min(780px,100%);max-height:94vh;overflow:auto;border-radius:16px;padding:18px;box-shadow:0 20px 60px rgba(0,0,0,.25)}.lh-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.lh-field{display:flex;flex-direction:column;gap:6px}.lh-field.full{grid-column:1/-1}.lh-field label{font-weight:700;font-size:14px}.lh-field input,.lh-field select,.lh-field textarea{box-sizing:border-box;width:100%;border:1px solid #cbd5e1;border-radius:10px;padding:11px;font-size:15px;background:#fff}.lh-levels{display:grid;grid-template-columns:repeat(5,1fr);gap:7px}.lh-level,.lh-comment{border:2px solid #cbd5e1;background:#fff;border-radius:10px;padding:10px;font-weight:700;cursor:pointer}.lh-level.active{border-color:#2563eb;background:#eff6ff}.lh-comments{display:grid;gap:7px;max-height:300px;overflow:auto}.lh-comment{text-align:left;border:1px solid #e2e8f0;background:#f8fafc;font-weight:400}.lh-comment.active{border-color:#2563eb;background:#eff6ff}.lh-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px;padding-top:10px;position:sticky;bottom:0;background:#fff}.lh-actions button{border:0;border-radius:10px;padding:12px 16px;font-weight:700}.lh-cancel{background:#e2e8f0}.lh-save{background:#2563eb;color:#fff;min-width:160px}.lh-error{color:#b91c1c;min-height:18px}@media(max-width:600px){#lhLearningModal{padding:0;align-items:flex-end}#lhLearningModal .lh-box{width:100%!important;max-height:96vh!important;border-radius:16px 16px 0 0!important}.lh-grid{grid-template-columns:1fr}.lh-field.full{grid-column:auto}.lh-levels{grid-template-columns:repeat(2,1fr)}.lh-actions{padding-bottom:calc(8px + env(safe-area-inset-bottom));position:sticky;bottom:0}.lh-save{flex:1}}';document.head.appendChild(s)}
function close(){document.getElementById('lhLearningModal')?.remove();level=''}
function open(){addStyle();close();const ss=students(),m=document.createElement('div');m.id='lhLearningModal';m.innerHTML='<div class="lh-box"><h2>📚 Ghi nhận kết quả học tập</h2><div class="lh-grid"><div class="lh-field"><label>Ngày</label><input id="lhDate" type="date" value="'+today()+'"></div><div class="lh-field"><label>Học sinh</label><select id="lhStudent"><option value="">Chọn học sinh</option>'+ss.map(s=>'<option value="'+esc(s.id||s.studentId)+'">'+esc(s.name||s.studentName)+'</option>').join('')+'</select></div><div class="lh-field full"><label>Môn học</label><select id="lhSubject"><option value="">Chọn môn học</option>'+SUBJECTS.map(s=>'<option value="'+esc(s)+'">'+esc(s)+'</option>').join('')+'</select></div><div class="lh-field full"><label>Mức đạt <small>(bắt buộc chọn)</small></label><div class="lh-levels" id="lhLevels">'+LEVELS.map(x=>'<button type="button" class="lh-level" data-level="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div></div><div class="lh-field full"><label>20 nhận xét theo đúng môn và mức đã chọn</label><div id="lhComments" class="lh-comments"><div>Chọn môn học và mức đạt.</div></div><textarea id="lhComment" rows="3" placeholder="Hoặc nhập nhận xét riêng..."></textarea></div><div class="lh-field full"><label>Nội dung</label><input id="lhContent" placeholder="Ví dụ: Phân số, đọc hiểu, chất..."></div><div class="lh-field full"><label>Ghi chú</label><input id="lhNote"></div><div class="lh-field full"><div id="lhError" class="lh-error"></div></div></div><div class="lh-actions"><button type="button" class="lh-cancel" id="lhCancel">Hủy</button><button type="button" class="lh-save" id="lhSave">💾 Lưu kết quả</button></div></div>';document.body.appendChild(m);m.querySelector('#lhCancel').onclick=close;m.querySelector('#lhSubject').onchange=()=>{level='';m.querySelectorAll('[data-level]').forEach(x=>x.classList.remove('active'));renderComments()};m.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=b.dataset.level;m.querySelectorAll('[data-level]').forEach(x=>x.classList.toggle('active',x===b));renderComments()});m.querySelector('#lhSave').onclick=save}
function renderComments(){const b=document.getElementById('lhComments'),s=document.getElementById('lhSubject')?.value,a=s&&level&&COMMENTS[s]&&COMMENTS[s][level]?COMMENTS[s][level]:[];if(!b)return;b.innerHTML=a.length?a.map((x,i)=>'<button type="button" class="lh-comment" data-i="'+i+'">'+esc(x)+'</button>').join(''):'<div>Chọn môn học và mức đạt.</div>';b.querySelectorAll('.lh-comment').forEach(x=>x.onclick=()=>{const c=document.getElementById('lhComment');c.value=a[Number(x.dataset.i)];b.querySelectorAll('.lh-comment').forEach(y=>y.classList.remove('active'));x.classList.add('active')})}
function save(){const e=document.getElementById('lhError'),st=document.getElementById('lhStudent'),su=document.getElementById('lhSubject'),co=document.getElementById('lhComment');e.textContent='';if(!st.value)return e.textContent='Chưa chọn học sinh.';if(!su.value)return e.textContent='Chưa chọn môn học.';if(!level)return e.textContent='Chưa chọn mức đạt.';if(!co.value.trim())return e.textContent='Chưa chọn hoặc nhập nhận xét.';const r={id:uid(),studentId:st.value,studentName:st.selectedOptions[0].textContent,date:document.getElementById('lhDate').value||today(),subject:su.value,content:document.getElementById('lhContent').value.trim(),resultType:'MUC_DAT',result:level,level,comment:co.value.trim(),note:document.getElementById('lhNote').value.trim(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};records.unshift(r);persist();close();renderOverview();if(typeof window.showToast==='function')window.showToast('Đã lưu kết quả học tập.');else alert('Đã lưu kết quả học tập.')}
function renderOverview(){const b=document.getElementById('learningOverview');if(!b)return;b.innerHTML='<div style="display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;margin-bottom:12px"><strong>'+records.length+' lượt đánh giá</strong><button type="button" class="button primary" id="lhOverviewAdd">➕ Ghi nhận kết quả</button></div>'+(records.length?'<div class="table-container"><table class="data-table"><thead><tr><th>Ngày</th><th>Học sinh</th><th>Môn</th><th>Mức đạt</th><th>Nhận xét</th></tr></thead><tbody>'+records.map(r=>'<tr><td>'+esc(r.date)+'</td><td>'+esc(r.studentName||r.studentId)+'</td><td>'+esc(r.subject)+'</td><td>'+esc(r.level||r.result)+'</td><td>'+esc(r.comment)+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty-state"><strong>Chưa có dữ liệu học tập</strong><p>Hãy bấm “Ghi nhận kết quả” để bắt đầu.</p></div>');const a=document.getElementById('lhOverviewAdd');if(a)a.onclick=open}
function init(){addStyle();document.addEventListener('click',e=>{const b=e.target.closest('[data-action="add-learning"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open()},{capture:true});window.renderLearning=renderOverview;window.LH_LEARNING_PHASE1={SUBJECTS,LEVELS,COMMENTS,open,close,renderOverview};renderOverview()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();