/* =========================================================
   HỌC TẬP — GIAI ĐOẠN 1 — GOOGLE SHEETS
   1 lượt = 1 dòng. Không đụng module khác.
   HOC_TAP hiện dùng schema: id, studentId, date, subject, result, level, note, createdAt, updatedAt.
   Các trường giao diện được đóng gói an toàn vào result/note để giữ nguyên schema hiện có.
   ========================================================= */
(function(){
'use strict';
const SUBJECTS=['Toán','Tiếng Việt','Khoa học','Lịch sử và Địa lí','Công nghệ','Tin học','Ngoại ngữ'];
const LEVELS=['Tốt','Đạt','Chưa đạt'];
const esc=v=>String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const now=()=>new Date().toISOString();
const today=()=>new Date().toISOString().slice(0,10);
function arr(){if(!Array.isArray(window.learningRecords))window.learningRecords=[];return window.learningRecords}
function students(){return Array.isArray(window.students)?window.students:(window.APP_DATA&&Array.isArray(window.APP_DATA.students)?window.APP_DATA.students:[])}
function sid(s){return s.id||s.studentId||s.ID||''}
function sname(id){const s=students().find(x=>String(sid(x))===String(id));return s?(s.name||s.hoTen||s.hoten||s.fullName||id):id}
function uid(){return'HT_'+Date.now()+'_'+Math.random().toString(36).slice(2,8)}
function toast(m){if(typeof window.showToast==='function')window.showToast(m);else alert(m)}
function api(){return window.GOOGLE_API_CONFIG&&window.GOOGLE_API_CONFIG.url}
function jsonp(action,params){return new Promise((resolve,reject)=>{const url=api();if(!url)return reject(Error('Chưa có kết nối Google Apps Script'));const cb='__LH_HT_'+Date.now()+'_'+Math.random().toString(36).slice(2),sc=document.createElement('script');let done=false;const finish=(e,d)=>{if(done)return;done=true;clearTimeout(timer);try{delete window[cb]}catch(_){}sc.remove();e?reject(e):resolve(d)};const timer=setTimeout(()=>finish(Error('Google Apps Script phản hồi quá thời gian')),20000);window[cb]=d=>finish(null,d);sc.onerror=()=>finish(Error('Không kết nối được Google Apps Script'));const q=Object.assign({action,callback:cb,_:Date.now()},params||{});sc.src=url+'?'+Object.keys(q).map(k=>encodeURIComponent(k)+'='+encodeURIComponent(typeof q[k]==='string'?q[k]:JSON.stringify(q[k]))).join('&');document.head.appendChild(sc)})}
function pack(r){return{result:JSON.stringify({content:r.content||'',resultType:r.resultType||'DIEM',score:r.score===''?'':r.score,comment:r.comment||''}),level:r.level||'',note:r.note||''}}
function unpack(r){let x={};try{x=JSON.parse(String(r.result||''))}catch(_){x={content:r.result||'',resultType:'DIEM',score:'',comment:''}}return Object.assign({},r,{content:x.content||'',resultType:x.resultType||'DIEM',score:x.score==null?'':x.score,comment:x.comment||'',note:r.note||''})}
async function saveRemote(r){const p=pack(r),record={id:r.id,studentId:r.studentId,date:r.date,subject:r.subject,result:p.result,level:p.level,note:p.note,createdAt:r.createdAt||now(),updatedAt:r.updatedAt||now()};const res=await jsonp('save_event',{payload:JSON.stringify({sheet:'HOC_TAP',record})});if(!res||res.ok!==true||res.saved!==true)throw Error(res&&res.error||'Google Sheets không xác nhận đã lưu');return res}
async function loadRemote(){try{const res=await jsonp('get_all');if(!res||res.ok!==true)return false;const incoming=(res.HOC_TAP||[]).map(unpack);window.learningRecords=incoming;if(window.APP_DATA)window.APP_DATA.learning=incoming;localStorage.setItem('learningRecords',JSON.stringify(incoming));render();return true}catch(e){console.warn('[HỌC TẬP]',e.message);return false}}
function openForm(editId){const old=arr().find(r=>String(r.id)===String(editId))||{},ss=students();const opts=ss.map(s=>{const id=sid(s),name=s.name||s.hoTen||s.hoten||s.fullName||id;return`<option value="${esc(id)}" ${String(id)===String(old.studentId||'')?'selected':''}>${esc(name)}</option>`}).join('');const so=SUBJECTS.map(x=>`<option ${x===old.subject?'selected':''}>${esc(x)}</option>`).join(''),lo=LEVELS.map(x=>`<option ${x===old.level?'selected':''}>${esc(x)}</option>`).join('');document.body.insertAdjacentHTML('beforeend',`<div id="learningModal" class="modal-overlay" style="display:flex;z-index:9999"><div class="modal-card" style="max-width:620px;width:94%;max-height:90vh;overflow:auto"><div class="modal-header"><h3>📝 ${editId?'Chỉnh sửa':'Ghi nhận'} kết quả học tập</h3><button type="button" onclick="window.closeLearningForm()">×</button></div><form id="learningForm"><input type="hidden" name="id" value="${esc(old.id||'')}"><label>Ngày<input type="date" name="date" value="${esc(old.date||today())}" required></label><label>Học sinh<select name="studentId" required><option value="">-- Chọn học sinh --</option>${opts}</select></label><label>Môn học<select name="subject" required><option value="">-- Chọn môn --</option>${so}</select></label><label>Nội dung<input name="content" value="${esc(old.content||'')}" placeholder="Ví dụ: Phân số" required></label><label>Loại kết quả<select name="resultType"><option value="DIEM" ${old.resultType==='DIEM'?'selected':''}>Điểm</option><option value="MUC_DAT" ${old.resultType==='MUC_DAT'?'selected':''}>Mức đạt</option><option value="NHAN_XET" ${old.resultType==='NHAN_XET'?'selected':''}>Nhận xét</option></select></label><label>Điểm (0–10)<input type="number" name="score" min="0" max="10" step="0.1" value="${esc(old.score??'')}" placeholder="Không bắt buộc"></label><label>Mức đạt<select name="level"><option value="">-- Không chọn --</option>${lo}</select></label><label>Nhận xét<textarea name="comment" rows="3" placeholder="Nhận xét về kết quả học tập">${esc(old.comment||'')}</textarea></label><label>Ghi chú<textarea name="note" rows="2">${esc(old.note||'')}</textarea></label><div class="modal-actions"><button type="button" onclick="window.closeLearningForm()">Hủy</button><button class="btn-primary" type="submit">💾 ${editId?'Cập nhật':'Lưu kết quả'}</button></div></form></div></div>`);document.getElementById('learningForm').addEventListener('submit',saveForm)}
async function saveForm(e){e.preventDefault();const f=new FormData(e.target),id=String(f.get('id')||uid()),score=String(f.get('score')||'').trim();if(score!==''&&(Number(score)<0||Number(score)>10))return toast('Điểm phải từ 0 đến 10.');const old=arr().find(r=>String(r.id)===id),item={id,studentId:String(f.get('studentId')||''),date:String(f.get('date')||''),subject:String(f.get('subject')||''),content:String(f.get('content')||''),resultType:String(f.get('resultType')||'DIEM'),score:score===''?'':Number(score),level:String(f.get('level')||''),comment:String(f.get('comment')||''),note:String(f.get('note')||''),createdAt:old&&old.createdAt||now(),updatedAt:now()};if(!item.studentId||!item.date||!item.subject||!item.content)return toast('Vui lòng nhập đủ Ngày, Học sinh, Môn học và Nội dung.');try{await saveRemote(item);const a=arr(),i=a.findIndex(r=>String(r.id)===id);if(i>=0)a[i]=item;else a.unshift(item);window.learningRecords=a;if(window.APP_DATA)window.APP_DATA.learning=a;localStorage.setItem('learningRecords',JSON.stringify(a));closeForm();render();toast(old?'Đã cập nhật và lưu vào Google Sheets.':'Đã lưu kết quả vào Google Sheets.')}catch(err){toast('LƯU THẤT BẠI: '+err.message);console.error(err)}}
function closeForm(){document.getElementById('learningModal')?.remove()}
async function deleteLearning(id){if(!confirm('Bạn có chắc muốn xóa lượt ghi nhận này?'))return;try{const res=await jsonp('delete_event',{sheet:'HOC_TAP',id});if(!res||res.ok!==true||res.deleted!==true)throw Error(res&&res.error||'Google Sheets không xác nhận xóa');window.learningRecords=arr().filter(r=>String(r.id)!==String(id));if(window.APP_DATA)window.APP_DATA.learning=window.learningRecords;localStorage.setItem('learningRecords',JSON.stringify(window.learningRecords));render();toast('Đã xóa lượt học tập trên Google Sheets.')}catch(e){toast('XÓA THẤT BẠI: '+e.message)}}
function render(){const root=document.querySelector('#page-learning')||document.querySelector('[data-page="learning"]');if(!root)return;const q=String(root.querySelector('#learningSearch')?.value||'').toLowerCase(),sub=root.querySelector('#learningSubject')?.value||'',tbody=root.querySelector('#learningTbody');if(!tbody)return;let a=arr().filter(r=>!q||sname(r.studentId).toLowerCase().includes(q)||String(r.content||'').toLowerCase().includes(q)).filter(r=>!sub||r.subject===sub);if(!a.length){tbody.innerHTML='<tr><td colspan="8" style="text-align:center;padding:28px">Chưa có dữ liệu học tập.<br><small>Hãy bấm “Ghi nhận kết quả” để bắt đầu.</small></td></tr>';return}tbody.innerHTML=a.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.date)}</td><td><strong>${esc(sname(r.studentId))}</strong></td><td>${esc(r.subject)}</td><td>${esc(r.content)}</td><td>${r.score!==''&&r.score!=null?esc(r.score):(esc(r.level)||'—')}</td><td>${esc(r.comment)||'—'}</td><td><button onclick="window.editLearning('${esc(r.id)}')">✏️</button> <button onclick="window.deleteLearning('${esc(r.id)}')">🗑️</button></td></tr>`).join('')}
window.openLearningForm=openForm;window.closeLearningForm=closeForm;window.editLearning=openForm;window.deleteLearning=deleteLearning;window.renderLearning=render;window.loadLearningRecords=loadRemote;
document.addEventListener('input',e=>{if(e.target.id==='learningSearch')render()});document.addEventListener('change',e=>{if(e.target.id==='learningSubject')render()});window.addEventListener('google-sheets-data-ready',()=>{const d=window.GOOGLE_SHEET_DATA;if(d&&Array.isArray(d.HOC_TAP)){window.learningRecords=d.HOC_TAP.map(unpack);render()}else loadRemote()});document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{loadRemote();render()},250));
})();