/* =========================================================
   HỌC TẬP — GIAI ĐOẠN 1 — MASTER V3
   Phạm vi duy nhất: module Học tập / learning-menu.js
   - 6 môn: Toán, Tiếng Việt, Khoa học, Lịch sử và Địa lí, Công nghệ, Đạo đức
   - 20 nhận xét / môn / mức Tốt-Đạt-Chưa đạt
   - Giao diện nhận xét chọn nhanh, lọc theo môn + mức
   - Lưu / tải lại / lọc / sửa / xóa bản ghi
   - Không thay đổi cấu trúc Google Sheets hiện hữu
   - Ưu tiên API học tập nếu hệ thống đã có; fallback localStorage để dữ liệu không mất khi tải lại
   ========================================================= */
(function(){
'use strict';
if(window.__LH_LEARNING_MODULE_V3__)return;
window.__LH_LEARNING_MODULE_V3__=true;
const SUBJECTS=['Toán','Tiếng Việt','Khoa học','Lịch sử và Địa lí','Công nghệ','Đạo đức'];
const LEVELS=['Tốt','Đạt','Chưa đạt'];
const STORAGE_KEY='LH_LEARNING_PHASE1_RECORDS_V3';
const COMMENTS=window.LH_LEARNING_COMMENTS||{};
function clean(v){return String(v==null?'':v).trim().replace(/\s+/g,' ')}
function uid(){return 'HT_'+Date.now()+'_'+Math.random().toString(36).slice(2,9)}
function today(){return new Date().toISOString().slice(0,10)}
function q(id){return document.getElementById(id)}
function esc(v){return clean(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function loadLocal(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function saveLocal(list){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(list))}catch(e){}}
let records=loadLocal();window.learningRecords=records;let editingId='';let selectedLevel='';
function normalizeRecord(r){return {id:r.id||uid(),date:r.date||today(),studentId:clean(r.studentId),subject:clean(r.subject),content:clean(r.content),resultType:r.resultType||'MUC_DAT',result:r.result??'',level:clean(r.level),comment:clean(r.comment||r.nhanXet),note:clean(r.note||r.ghiChu),createdAt:r.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}}
function persist(){saveLocal(records);window.learningRecords=records;if(window.APP_DATA)window.APP_DATA.learning=records;window.dispatchEvent(new CustomEvent('learning-data-updated',{detail:records}))}
function remoteSave(rec){try{if(typeof window.saveLearningRecord==='function')return Promise.resolve(window.saveLearningRecord(rec));if(typeof window.saveLearningResult==='function')return Promise.resolve(window.saveLearningResult(rec));if(typeof window.saveRecordToGoogleSheets==='function'&&window.GOOGLE_LEARNING_API)return Promise.resolve(window.saveRecordToGoogleSheets('HOC_TAP',rec))}catch(e){return Promise.reject(e)}return Promise.resolve(null)}
function refreshComments(){const box=q('lhCommentList'),sub=q('lhSubject');if(!box||!sub)return;const level=selectedLevel||'';const arr=(COMMENTS[sub.value]&&COMMENTS[sub.value][level])||[];box.innerHTML=arr.length?arr.map((x,i)=>`<button type="button" class="lh-comment-item" data-comment-index="${i}">${esc(x)}</button>`).join(''):'<div class="lh-empty">Chọn môn và mức đánh giá để xem nhận xét phù hợp.</div>';box.querySelectorAll('[data-comment-index]').forEach(b=>b.onclick=()=>{q('lhComment').value=arr[Number(b.dataset.commentIndex)]||''})}
function resetForm(){['lhStudent','lhSubject','lhContent','lhScore','lhComment','lhNote'].forEach(id=>{const e=q(id);if(e)e.value=''});if(q('lhDate'))q('lhDate').value=today();if(q('lhResultType'))q('lhResultType').value='MUC_DAT';selectedLevel='';editingId='';if(q('lhScoreField'))q('lhScoreField').style.display='none';if(q('lhLevels'))q('lhLevels').querySelectorAll('.lh-level').forEach(x=>x.classList.remove('active'));refreshComments()}
function render(){const body=q('lhRows');if(!body)return;let list=records.slice();const search=clean(q('lhSearch')?.value).toLowerCase(),sub=q('lhFilterSubject')?.value||'',lev=q('lhFilterLevel')?.value||'';if(search)list=list.filter(r=>clean(r.studentName||r.studentId).toLowerCase().includes(search));if(sub)list=list.filter(r=>r.subject===sub);if(lev)list=list.filter(r=>r.level===lev);body.innerHTML=list.length?list.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.date)}</td><td>${esc(r.studentName||r.studentId)}</td><td>${esc(r.subject)}</td><td>${esc(r.content)}</td><td>${esc(r.resultType==='DIEM'?r.result:r.level)}</td><td>${esc(r.comment)}</td><td><button type="button" data-edit="${esc(r.id)}">Sửa</button> <button type="button" data-delete="${esc(r.id)}">Xóa</button></td></tr>`).join(''):'<tr><td colspan="8" class="lh-empty">Chưa có dữ liệu học tập</td></tr>';body.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editForm(b.dataset.edit));body.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteRecord(b.dataset.delete));if(q('lhRecordSummary'))q('lhRecordSummary').textContent=records.length+' lượt đánh giá'}
function editForm(id){const r=records.find(x=>x.id===id);if(!r)return;editingId=id;q('lhLearningFormPanel').hidden=false;q('lhDate').value=r.date;q('lhStudent').value=r.studentId;q('lhSubject').value=r.subject;q('lhContent').value=r.content;q('lhResultType').value=r.resultType||'MUC_DAT';q('lhScore').value=r.resultType==='DIEM'?r.result:'';q('lhComment').value=r.comment;q('lhNote').value=r.note;selectedLevel=r.level;refreshComments();if(q('lhScoreField'))q('lhScoreField').style.display=r.resultType==='DIEM'?'flex':'none';q('lhLearningFormPanel').scrollIntoView({behavior:'smooth',block:'start'})}
async function deleteRecord(id){if(!confirm('Xóa kết quả học tập này?'))return;records=records.filter(x=>x.id!==id);persist();render()}
async function saveForm(){const date=clean(q('lhDate')?.value)||today(),studentId=clean(q('lhStudent')?.value),subject=clean(q('lhSubject')?.value),comment=clean(q('lhComment')?.value),type=clean(q('lhResultType')?.value)||'MUC_DAT',score=clean(q('lhScore')?.value),content=clean(q('lhContent')?.value),note=clean(q('lhNote')?.value);if(!studentId||!subject||!selectedLevel||!comment){alert('Vui lòng chọn học sinh, môn học, mức đánh giá và nhận xét.');return}if(type==='DIEM'&&(score===''||Number(score)<0||Number(score)>10)){alert('Điểm phải từ 0 đến 10.');return}const old=editingId?records.find(x=>x.id===editingId):null;const student=q('lhStudent')?.selectedOptions?.[0]?.textContent||studentId;const rec=normalizeRecord({id:editingId||uid(),date,studentId,studentName:student,subject,content,resultType:type,result:type==='DIEM'?score:selectedLevel,level:selectedLevel,comment,note,createdAt:old?.createdAt});try{await remoteSave(rec)}catch(e){console.warn('Learning remote save fallback:',e)}const idx=records.findIndex(x=>x.id===rec.id);if(idx>=0)records[idx]=rec;else records.unshift(rec);persist();render();q('lhLearningFormPanel').hidden=true;resetForm();alert('Đã lưu kết quả học tập.');}
function bind(){const save=q('lhSave');if(save){save.type='button';save.textContent='💾 Lưu kết quả';save.style.display='inline-flex';save.onclick=saveForm}const cancel=q('lhCancel');if(cancel)cancel.onclick=()=>{q('lhLearningFormPanel').hidden=true;resetForm()};if(q('lhSubject'))q('lhSubject').onchange=refreshComments;if(q('lhResultType'))q('lhResultType').onchange=()=>{if(q('lhScoreField'))q('lhScoreField').style.display=q('lhResultType').value==='DIEM'?'flex':'none'};if(q('lhShuffleComment'))q('lhShuffleComment').onclick=refreshComments;if(q('lhSearch'))q('lhSearch').oninput=render;if(q('lhFilterSubject'))q('lhFilterSubject').onchange=render;if(q('lhFilterLevel'))q('lhFilterLevel').onchange=render;if(q('lhFilterPeriod'))q('lhFilterPeriod').onchange=render;if(q('lhLevels'))q('lhLevels').querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{selectedLevel=b.dataset.level;q('lhLevels').querySelectorAll('.lh-level').forEach(x=>x.classList.toggle('active',x===b));refreshComments()});render()}
function ensureSaveButton(){const panel=q('lhLearningFormPanel');if(!panel)return;let save=q('lhSave');if(!save){const actions=panel.querySelector('.lh-actions')||panel.lastElementChild;save=document.createElement('button');save.id='lhSave';save.type='button';save.className='lh-btn primary';save.textContent='💾 Lưu kết quả';(actions||panel).appendChild(save)}save.style.display='inline-flex';save.onclick=saveForm}
function init(){const run=()=>{ensureSaveButton();bind();refreshComments();render()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();setTimeout(ensureSaveButton,300);setTimeout(ensureSaveButton,1000)}
window.LH_LEARNING_PHASE1={SUBJECTS,LEVELS,refreshComments,saveForm,render,ensureSaveButton};init();
})();