/* MASTER CRUD UI — CANONICAL FAST v9
 * Single SAVE/DELETE owner. No post-save polling.
 * Apps Script Master contract: GET save_event/delete_event with JSONP.
 */
(function(){
'use strict';
if(window.__LH_MASTER_CRUD_UI__)return;
window.__LH_MASTER_CRUD_UI__=true;
const API='https://script.google.com/macros/s/AKfycbxTPwf-jhrR8JOoKY5ZLuzlsDgcv3nWILtDPTrYNWZCEPpm2rkpXTn-sPAdFaUyy0z_uw/exec';
const S=v=>String(v??'').trim();
const arr={VI_PHAM:'violationRecords',KHEN_THUONG:'rewardRecords',DIEM_DANH:'attendanceRecords',HOC_TAP:'learningRecords',TIEN_BO:'progressRecords',NHAN_XET:'commentRecords'};
const toast=(m,t='info')=>{try{window.showToast?window.showToast(m,t):console.log(m)}catch(_){}};
const id=p=>`${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb='__LH_FAST_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7),s=document.createElement('script');let done=false;const end=(e,v)=>{if(done)return;done=true;clearTimeout(t);try{delete window[cb]}catch(_){}s.remove();e?reject(e):resolve(v)};const t=setTimeout(()=>end(Error('Google Apps Script không phản hồi sau 15 giây.')),15000);window[cb]=v=>end(null,v);s.onerror=()=>end(Error('Không kết nối được Google Apps Script.'));const q=new URLSearchParams({action,callback:cb,_:Date.now()});Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null)q.set(k,typeof v==='string'?v:JSON.stringify(v))});s.src=(window.GOOGLE_API_CONFIG?.url||API)+'?'+q;document.head.appendChild(s)})}
function localUpsert(sheet,r){const name=arr[sheet],a=Array.isArray(window[name])?window[name]:null;if(!a||!r?.id)return;const i=a.findIndex(x=>S(x?.id)===S(r.id));if(i<0)a.push(r);else a[i]=r;try{window.syncAppDataReferences?.();window.saveClassData?.()}catch(_){} }
function localRemove(sheet,rid){const name=arr[sheet],a=Array.isArray(window[name])?window[name]:null;if(!a)return;for(let i=a.length-1;i>=0;i--)if(S(a[i]?.id)===S(rid))a.splice(i,1);try{window.syncAppDataReferences?.();window.saveClassData?.()}catch(_){} }
async function saveMaster(sheet,record){if(!sheet||!record?.studentId)throw Error('Thiếu sheet hoặc học sinh.');const r=await jsonp('save_event',{payload:JSON.stringify({sheet,record})});if(!r?.ok||!(r.saved===true||r.stored===true||r.success===true))throw Error(S(r?.error||r?.message||'Google Sheets không xác nhận lưu.'));const saved={...record,id:S(r.id)||S(record.id)};localUpsert(sheet,saved);return saved}
async function deleteMaster(sheet,rid){rid=S(rid);if(!sheet||!rid)throw Error('Thiếu sheet hoặc recordId.');const r=await jsonp('delete_event',{sheet,id:rid,recordId:rid});if(!r?.ok||!(r.deleted===true||r.success===true))throw Error(S(r?.error||r?.message||'Google Sheets không xác nhận xóa.'));localRemove(sheet,rid);return true}
function wrapSave(name,sheet,builder){const install=()=>{const old=window[name];if(typeof old!=='function'||old.__lhMasterFast)return false;const fn=function(...args){let rec;try{rec=builder(...args)}catch(e){toast('Lưu thất bại: '+S(e.message),'error');return{success:false}}if(!rec||!S(rec.studentId))return old.apply(this,args);rec={...rec,id:S(rec.id)||id(sheet==='VI_PHAM'?'VIO':sheet==='KHEN_THUONG'?'REW':sheet==='DIEM_DANH'?'ATT':'REC'),createdAt:S(rec.createdAt)||new Date().toISOString(),updatedAt:new Date().toISOString()};return saveMaster(sheet,rec).then(r=>{try{window.renderViolations?.();window.renderRewards?.();window.renderAttendance?.();window.renderDashboard?.();window.updateBadges?.()}catch(_){}toast('Đã lưu vào Google Sheets.','success');return{success:true,record:r}}).catch(e=>{toast('Lưu thất bại: '+S(e.message),'error');return{success:false,message:S(e.message)}})};fn.__lhMasterFast=true;fn.__lhMasterOriginal=old;window[name]=fn;return true};let n=0;const tm=setInterval(()=>{if(install()||++n>80)clearInterval(tm)},250);install()}
wrapSave('saveAttendanceRecord','DIEM_DANH',(studentId,date,status,note='')=>({studentId,date:date||today(),status,note}));
wrapSave('addViolation','VI_PHAM',d=>({...d}));
wrapSave('updateViolation','VI_PHAM',(rid,c={})=>{const o=(window.violationRecords||[]).find(x=>S(x?.id)===S(rid));return{...o,...c,id:S(rid)}});
wrapSave('addReward','KHEN_THUONG',d=>({...d}));
wrapSave('updateReward','KHEN_THUONG',(rid,c={})=>{const o=(window.rewardRecords||[]).find(x=>S(x?.id)===S(rid));return{...o,...c,id:S(rid)}});
wrapSave('addLearningRecord','HOC_TAP',d=>({...d}));wrapSave('addProgressRecord','TIEN_BO',d=>({...d}));wrapSave('addComment','NHAN_XET',d=>({...d}));
function installModalHandler(){if(window.__LH_FAST_MODAL__)return;window.__LH_FAST_MODAL__=true;const saveModal=async(modal,b,isV)=>{if(modal.dataset.lhSaving==='1')return;modal.dataset.lhSaving='1';const old=b.innerHTML;b.disabled=true;b.innerHTML='Đang lưu...';try{const pick=[...modal.querySelectorAll('.lh-csp-list input[type="checkbox"]:checked')].map(x=>S(x.value)).filter(Boolean);const fallback=S(modal.querySelector('#eStudent,#violationStudent,#rewardStudent')?.value);const students=[...new Set(pick.length?pick:(fallback?[fallback]:[]))];const type=S(modal.querySelector('#eType,#violationType,#rewardType')?.value);const date=S(modal.querySelector('#eDate,#violationDate,#rewardDate')?.value)||today();const note=S(modal.querySelector('#eNote,#violationNote,#rewardNote')?.value);if(!students.length)throw Error('Vui lòng chọn ít nhất một học sinh.');if(!type)throw Error('Vui lòng chọn nội dung.');const sheet=isV?'VI_PHAM':'KHEN_THUONG';for(const sid of students){const r={id:id(isV?'VIO':'REW'),studentId:sid,studentName:(window.students||[]).find(x=>S(x.id)===sid)?.name||'',date,type,note,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};if(isV){r.level=S(modal.querySelector('#eLevel,#violationLevel')?.value)||'light';r.status=S(modal.querySelector('#eStatus,#violationStatus')?.value)||'monitoring';r.action=S(modal.querySelector('#eAction,#violationAction')?.value)||''}else r.formType=S(modal.querySelector('#eForm,#rewardFormType')?.value)||'praise';await saveMaster(sheet,r)}try{window.renderViolations?.();window.renderRewards?.();window.renderDashboard?.();window.updateBadges?.()}catch(_){}modal.remove();toast(`Đã lưu ${students.length} học sinh vào Google Sheets.`,'success')}catch(e){toast('Lưu thất bại: '+S(e.message),'error')}finally{modal.dataset.lhSaving='';b.disabled=false;b.innerHTML=old}};window.addEventListener('click',e=>{const t=e.target instanceof Element?e.target:null;if(!t)return;const m=t.closest('.ev-static-modal');if(m){const b=t.closest('#eSave');if(b){e.preventDefault();e.stopImmediatePropagation();saveModal(m,b,!!m.querySelector('#eLevel'));return}}const f=t.closest('#violationForm,#rewardForm');const b=t.closest('button');if(f&&b&&(b.type==='submit'||/\blưu\b/i.test(S(b.textContent)))){e.preventDefault();e.stopImmediatePropagation();saveModal(f,b,f.id==='violationForm')}} ,true)}installModalHandler();window.LH_MASTER_CRUD={saveMaster,deleteMaster};
})();
