/* TIỆN ÍCH LỚP HỌC — SƠ ĐỒ LỚP / TRÌNH ĐỘ THỰC TẾ */
(function(){
'use strict';
if(window.__LH_TI_ICH_30__)return;window.__LH_TI_ICH_30__=true;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const clean=v=>String(v??'').trim(),norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
function students(){try{if(typeof window.getStudentsSafe==='function'){const a=window.getStudentsSafe();if(Array.isArray(a))return a.filter(x=>x&&x.id&&x.name)}}catch(_){}return Array.isArray(window.students)?window.students.filter(x=>x&&x.id&&x.name):[]}
function learningRecords(){const keys=['learningRecords','hocTapRecords','hocTapData','learningData'];for(const k of keys)if(Array.isArray(window[k]))return window[k];return[]}
function levelOf(s){const direct=s?.xepLoai||s?.xepLoaiHocTap||s?.academicLevel||s?.learningLevel||s?.level||s?.classification||s?.result||s?.hocLuc||s?.trinhDo||s?.trinhDoHocTap||s?.mucDo;if(clean(direct))return clean(direct);const rows=learningRecords().filter(r=>String(r?.studentId||'')===String(s?.id||''));for(let i=rows.length-1;i>=0;i--){const v=rows[i]?.level||rows[i]?.xepLoai||rows[i]?.result;if(clean(v))return clean(v)}return'Chưa xác định'}
function rank(v){const n=norm(v);if(/tot|gioi|xuat sac|hoan thanh tot/.test(n))return 3;if(/kha|dat|hoan thanh/.test(n))return 2;if(/trung binh|yeu|kem|chua dat/.test(n))return 1;return 0}
function ensurePage(){let p=$('page-utilities');if(p)return p;p=document.createElement('section');p.className='page-section';p.id='page-utilities';p.dataset.pageSection='utilities';const main=$('mainContent');if(!main)return null;main.appendChild(p);return p}
function renderShell(){const p=ensurePage();if(!p)return null;p.innerHTML=`<div class="page-header"><div><span class="page-eyebrow"><i class="fa-solid fa-toolbox"></i> Công cụ giáo viên</span><h1>Tiện ích</h1><p>Sắp xếp sơ đồ lớp theo trình độ thực tế, ngẫu nhiên và phân bố đồng đều.</p></div></div><div class="dashboard-panel"><div class="panel-header"><div><h3>🧰 Tiện ích lớp học</h3><p>Mỗi bàn 2 học sinh · mỗi dãy bàn là 1 tổ.</p></div></div><div class="quick-actions" id="lhUtilityActions"><button type="button" class="quick-action" data-lh-util="levels"><span class="quick-action-icon"><i class="fa-solid fa-list-ol"></i></span><span><strong>Tải danh sách trình độ HS</strong><small>TT · Họ tên HS · Xếp loại thực tế</small></span></button><button type="button" class="quick-action" data-lh-util="seating"><span class="quick-action-icon"><i class="fa-solid fa-chair"></i></span><span><strong>Tạo sơ đồ lớp học</strong><small>2 học sinh/bàn · ngẫu nhiên cân bằng trình độ</small></span></button></div><div id="lhUtilityWork"></div></div>`;return p}
function renderLevels(){const list=students().map((s,i)=>({tt:i+1,name:s.name,level:levelOf(s)}));const work=$('lhUtilityWork');if(!work)return;const counts={};list.forEach(x=>counts[x.level]=(counts[x.level]||0)+1);work.innerHTML=`<div class="panel-header"><div><h3>📋 Danh sách học sinh theo trình độ thực tế</h3><p>${list.length} học sinh · Chỉ sử dụng dữ liệu trình độ đã có; không tự bịa xếp loại.</p></div></div><div class="table-container"><table class="data-table"><thead><tr><th>TT</th><th>Họ tên HS</th><th>Xếp loại</th></tr></thead><tbody>${list.map(x=>`<tr><td>${x.tt}</td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.level)}</td></tr>`).join('')}</tbody></table></div><div class="panel-header" style="margin-top:16px"><div><h3>Phân bố trình độ</h3><p>${Object.entries(counts).map(([k,v])=>esc(k)+': '+v).join(' · ')}</p></div></div>`}
function shuffled(a){return [...a].sort(()=>Math.random()-.5)}
function makePairs(list){const buckets={3:shuffled(list.filter(s=>rank(levelOf(s))===3)),2:shuffled(list.filter(s=>rank(levelOf(s))===2)),1:shuffled(list.filter(s=>rank(levelOf(s))===1)),0:shuffled(list.filter(s=>rank(levelOf(s))===0))};const pool=[...buckets[3],...buckets[2],...buckets[1],...buckets[0]],pairs=[];while(pool.length){const first=pool.shift();let idx=pool.findIndex(s=>rank(levelOf(s))!==rank(levelOf(first)));if(idx<0)idx=0;const second=idx>=0?pool.splice(idx,1)[0]:null;pairs.push(second?[first,second]:[first])}return shuffled(pairs)}
function seating(){const list=students();if(!list.length){alert('Chưa có danh sách học sinh.');return}const cols=Math.max(1,Number(prompt('Số dãy bàn (mỗi dãy là một tổ)?','4'))||4);const pairs=makePairs(list);const rows=Array.from({length:cols},()=>[]);pairs.forEach((pair,i)=>rows[i%cols].push(pair));const maxDesks=Math.max(...rows.map(a=>a.length));let body='';for(let r=0;r<maxDesks;r++){body+=`<tr><td><strong>Bàn ${r+1}</strong></td>`;for(let c=0;c<cols;c++){const pair=rows[c][r];body+=`<td>${pair?pair.map(s=>`<div><strong>${esc(s.name)}</strong> <small>(${esc(levelOf(s))})</small></div>`).join(''):'—'}</td>`}body+='</tr>'}const counts={};list.forEach(s=>counts[levelOf(s)]=(counts[levelOf(s)]||0)+1);const work=$('lhUtilityWork');if(!work)return;work.innerHTML=`<div class="panel-header"><div><h3>📐 Sơ đồ lớp học — ngẫu nhiên cân bằng</h3><p>${list.length} học sinh · ${cols} dãy/tổ · mỗi bàn 2 học sinh · ${maxDesks} bàn tối đa/dãy</p></div></div><div class="table-container"><table class="data-table"><thead><tr><th>Bàn</th>${Array.from({length:cols},(_,i)=>`<th>Dãy ${i+1} — Tổ ${i+1}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div><div class="panel-header" style="margin-top:16px"><div><h3>🎯 Nguyên tắc xếp</h3><p>Ưu tiên ghép hai học sinh khác trình độ trong cùng bàn; sau đó phân bổ các bàn vòng tròn giữa các dãy để các tổ có cơ cấu trình độ gần đồng đều. Thứ tự được xáo trộn lại mỗi lần tạo sơ đồ.</p><p><strong>Phân bố thực tế:</strong> ${Object.entries(counts).map(([k,v])=>esc(k)+': '+v).join(' · ')}</p></div></div>`}
function install(){renderShell();const nav=document.querySelector('.main-menu');if(nav&&!nav.querySelector('[data-page="utilities"]')){const b=document.createElement('button');b.type='button';b.className='menu-item';b.dataset.page='utilities';b.innerHTML='<i class="fa-solid fa-toolbox"></i><span>Tiện ích</span>';const settings=nav.querySelector('[data-page="settings"]');if(settings)nav.insertBefore(b,settings);else nav.appendChild(b)}document.addEventListener('click',e=>{const b=e.target.closest?.('[data-lh-util]');if(!b)return;if(b.dataset.lhUtil==='levels')renderLevels();if(b.dataset.lhUtil==='seating')seating()},{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();