/* TIỆN ÍCH LỚP HỌC — sơ đồ lớp / chia tổ */
(function(){
'use strict';
if(window.__LH_TI_ICH_10__)return;window.__LH_TI_ICH_10__=true;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function students(){try{if(typeof window.getStudentsSafe==='function'){const a=window.getStudentsSafe();if(Array.isArray(a))return a.filter(x=>x&&x.id&&x.name)}}catch(_){}return Array.isArray(window.students)?window.students.filter(x=>x&&x.id&&x.name):[]}
function ensurePage(){let p=$('page-utilities');if(p)return p;p=document.createElement('section');p.className='page-section';p.id='page-utilities';p.dataset.pageSection='utilities';p.innerHTML=`<div class="page-header"><div><span class="page-eyebrow"><i class="fa-solid fa-toolbox"></i> Công cụ giáo viên</span><h1>Tiện ích</h1><p>Các công cụ hỗ trợ tổ chức lớp học nhanh và trực quan.</p></div></div><div class="dashboard-panel"><div class="panel-header"><div><h3>🧰 Tiện ích lớp học</h3><p>Chọn công cụ cần sử dụng.</p></div></div><div class="quick-actions" id="lhUtilityActions"><button type="button" class="quick-action" data-lh-util="seating"><span class="quick-action-icon"><i class="fa-solid fa-chair"></i></span><span><strong>Tạo sơ đồ lớp học</strong><small>Sắp xếp học sinh theo hàng và bàn</small></span></button><button type="button" class="quick-action" data-lh-util="groups"><span class="quick-action-icon"><i class="fa-solid fa-people-group"></i></span><span><strong>Chia tổ</strong><small>Chia đều học sinh thành các tổ</small></span></button><button type="button" class="quick-action" data-lh-util="shuffle"><span class="quick-action-icon"><i class="fa-solid fa-shuffle"></i></span><span><strong>Xáo trộn học sinh</strong><small>Tạo thứ tự ngẫu nhiên để chia nhóm</small></span></button></div><div id="lhUtilityWork"></div></div>`;const main=$('mainContent');if(main)main.appendChild(p);return p}
function seating(){const list=students();const cols=Math.max(1,Number(prompt('Số bàn mỗi hàng?','3'))||3);const rows=Math.ceil(list.length/cols);const work=$('lhUtilityWork');if(!work)return;let html='<div class="table-container"><table class="data-table"><thead><tr><th>Hàng</th>'+Array.from({length:cols},(_,i)=>`<th>Bàn ${i+1}</th>`).join('')+'</tr></thead><tbody>';for(let r=0;r<rows;r++){html+=`<tr><td><strong>Hàng ${r+1}</strong></td>`;for(let c=0;c<cols;c++){const s=list[r*cols+c];html+=`<td>${s?esc(s.name):'—'}</td>`}html+='</tr>'}html+='</tbody></table></div>';work.innerHTML='<div class="panel-header"><div><h3>📐 Sơ đồ lớp học</h3><p>'+list.length+' học sinh · '+rows+' hàng · '+cols+' bàn/hàng</p></div></div>'+html}
function groups(){const list=students();const n=Math.max(1,Number(prompt('Chia thành bao nhiêu tổ?','4'))||4);const shuffled=[...list].sort(()=>Math.random()-.5);const gs=Array.from({length:Math.min(n,Math.max(1,list.length))},()=>[]);shuffled.forEach((s,i)=>gs[i%gs.length].push(s));const work=$('lhUtilityWork');if(!work)return;work.innerHTML='<div class="dashboard-columns">'+gs.map((g,i)=>`<section class="dashboard-panel"><div class="panel-header"><div><h3>👥 Tổ ${i+1}</h3><p>${g.length} học sinh</p></div></div><ol>${g.map(s=>`<li>${esc(s.name)}</li>`).join('')}</ol></section>`).join('')+'</div>'}
function shuffle(){const list=students();const shuffled=[...list].sort(()=>Math.random()-.5);const work=$('lhUtilityWork');if(!work)return;work.innerHTML='<div class="dashboard-panel"><div class="panel-header"><div><h3>🔀 Thứ tự ngẫu nhiên</h3><p>Đã tạo thứ tự mới cho '+shuffled.length+' học sinh.</p></div></div><ol>'+shuffled.map(s=>`<li>${esc(s.name)}</li>`).join('')+'</ol></div>'}
function install(){const p=ensurePage();let nav=document.querySelector('.main-menu');if(nav&&!nav.querySelector('[data-page="utilities"]')){const b=document.createElement('button');b.type='button';b.className='menu-item';b.dataset.page='utilities';b.innerHTML='<i class="fa-solid fa-toolbox"></i><span>Tiện ích</span>';const settings=nav.querySelector('[data-page="settings"]');if(settings)nav.insertBefore(b,settings);else nav.appendChild(b)}document.addEventListener('click',e=>{const b=e.target.closest?.('[data-lh-util]');if(!b)return;const k=b.dataset.lhUtil;if(k==='seating')seating();if(k==='groups')groups();if(k==='shuffle')shuffle()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();