(function(){'use strict';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const clean=v=>String(v??'').trim();
function LHStudents(){try{if(typeof window.getStudentsSafe==='function'){const a=window.getStudentsSafe();if(Array.isArray(a))return a.filter(x=>x&&x.id&&x.name)}}catch(e){}return Array.isArray(window.students)?window.students.filter(x=>x&&x.id&&x.name):[]}
function LHRecords(){for(const k of ['learningRecords','hocTapRecords','hocTapData','learningData'])if(Array.isArray(window[k]))return window[k];return[]}
function LHLevel(s){const v=s?.xepLoai||s?.xepLoaiHocTap||s?.academicLevel||s?.learningLevel||s?.classification||s?.hocLuc||s?.trinhDo||s?.trinhDoHocTap||s?.mucDo;if(clean(v))return clean(v);const a=LHRecords().filter(r=>String(r?.studentId||'')===String(s?.id||''));for(let i=a.length-1;i>=0;i--){const x=a[i]?.level||a[i]?.xepLoai||a[i]?.result;if(clean(x))return clean(x)}return'Chưa xác định'}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"'}
function download(){const a=LHStudents();if(!a.length){alert('Chưa có danh sách học sinh để tải.');return}const rows=[['TT','Họ tên HS','Xếp loại'],...a.map((s,i)=>[i+1,s.name,LHLevel(s)])];const csv='\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='DANH_SACH_TRINH_DO_HS.csv';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function install(){const old=document.getElementById('lhLevels');if(old){old.textContent='';old.innerHTML='<span class="quick-action-icon">📥</span><span><strong>Tải danh sách trình độ HS</strong><small>CSV: TT · Họ tên HS · Xếp loại thực tế</small></span>';old.onclick=download}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();