/* TIỆN ÍCH LỚP HỌC — SƠ ĐỒ LỚP / TRÌNH ĐỘ THỰC TẾ */
(function(){
'use strict';
if(window.__LH_TI_ICH_20__)return;window.__LH_TI_ICH_20__=true;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();
function students(){try{if(typeof window.getStudentsSafe==='function'){const a=window.getStudentsSafe();if(Array.isArray(a))return a.filter(x=>x&&x.id&&x.name)}}catch(_){}return Array.isArray(window.students)?window.students.filter(x=>x&&x.id&&x.name):[]}
function levelOf(s){return clean(s?.xepLoai||s?.xepLLoai||s?.xepLoaiHocTap||s?.academicLevel||s?.learningLevel||s?.level||s?.classification||s?.result||s?.hocLuc||s?.trinhDo||s?.trinhDoHocTap||s?.mucDo||'Chưa xác định')}
function rankLevel(v){const n=norm(v);if(/(tot|gioi|hoan thanh tot|xuat sac|tốt|giỏi|hoàn thành tốt|xuất sắc)/.test(n))return 3;if(/(kha|dat|hoan thanh|khá|đạt|hoàn thành)/.test(n))return 2;if(/(trung binh|trungbinh|chua dat|yeu|kem|chưa đạt|yếu|kém)/.test(n))return 1;return 0}
function ensurePage(){let p=$('page-utilities');if(p){p.innerHTML=`<div class="page-header"><div><span class="page-eyebrow"><i class="fa-solid fa-toolbox"></i> Công cụ giáo viên</span><h1>Tiện ích</h1><p>Sơ đồ lớp được xếp ngẫu nhiên nhưng cân bằng trình độ thực tế của lớp.</p></div></div><div class="dashboard-panel"><div class="panel-header"><div><h3>🧰 Tiện ích lớp học</h3><p>Mỗi bàn 2 học sinh; mỗi dãy bàn là một tổ.</p></div></div><div class="quick-actions" id="lhUtilityActions"><button type="button" class="quick-action" data-lh-util="levels"><span class="quick-action-icon"><i class="fa-solid fa-list-ol"></i></span><span><strong>Tải danh sách trình độ HS</strong><small>TT · Họ tên HS · Xếp loại thực tế</small></span></button><button type="button" class="quick-action" data-lh-util="seating"><span class="quick-action-icon"><i class="fa-solid fa-chair"></i></span><span><strong>Tạo sơ đồ lớp học</strong><small>2 học sinh/bàn · phân bố ngẫu nhiên, đồng đều trình độ</small></span></button></div><div id="lhUtilityWork"></div></div>`;return p}p=document.createElement('section');p.className='page-section';p.id='page-utilities';p.dataset.pageSection='utilities';const main=$('mainContent');if(!main)return null;main.appendChild(p);return ensurePage()}
function renderLevels(){const list=students().map((s,i)=>({tt:i+1,name:s.name,level:levelOf(s)}));const work=$('lhUtilityWork');if(!work)return;const counts={};list.forEach(x=>counts[x.level]=(counts[x.level]||0)+1);work.innerHTML=`<div class="panel-header"><div><h3>📋 Danh sách học sinh theo trình độ thực tế</h3><p>${list.length} học sinh · Dữ liệu đọc từ danh sách hiện có, không tự bịa xếp loại.</p></div></div><div class="table-container"><table class="data-table"><thead><tr><th>TT</th><th>Họ tên HS</th><th>Xếp loại</th></tr></thead><tbody>${list.map(x=>`<tr><td>${x.tt}</td><td><strong>${esc(x.name)}</strong></td><td>${esc(x.level)}</td></tr>`).join('')}</tbody></table></div><div class="panel-header" style="margin-top:16px"><div><h3>Phân bố trình độ</h3><p>${Object.entries(counts).map(([k,v])=>esc(k)+': '+v).join(' · ')}</p></div></div>`}
function shuffleSeed(list){return [...list].sort(()=>Math.random()-.5)}
function balancedOrder(list){const buckets=new Map();list.forEach(s=>{const k=levelOf(s);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(s)});const groups=[...buckets.values()].map(shuffleSeed).sort((a,b)=>b.length-a.length);const out=[];let left=true;while(groups.some(g=>g.length)){for(let i=0;i<groups.length;i++){const g=groups[i];if(!g.length)continue;const s=g.shift();out.push(s)}groups.sort((a,b)=>b.length-a.length)}return shuffleSeed(out)}
function seating(){const list=students();if(!list.length){alert('Chưa có danh sách học sinh.');return}const cols=Math.max(1,Number(prompt('Số dãy bàn (mỗi dãy là 1 tổ)?','4'))||4);const desks=Math.ceil(list.length/(cols*2));const order=balancedOrder(list);const seats=Array.from({length:cols},()=>[]);order.forEach((s,i)=>{seats[i%cols].push(s)});seats.forEach(col=>col.sort((a,b)=>0));const maxDesks=Math.max(...seats.map(a=>Math.ceil(a.length/2)));let html='';for(let r=0;r<maxDesks;r++){html+=`<tr><td><strong>Bàn ${r+1}</strong></td>`;for(let c=0;c<cols;c++){const a=seats[c][r*2],b=seats[c][r*2+1];html+=`<td>${a?`<div>${esc(a.name)} <small>(${esc(levelOf(a))})</small></div>`:''}${b?`<div>${esc(b.name)} <small>(${esc(levelOf(b))})</small></div>`:' '}</td>`}html+='</tr>'}const work=$('lhUtilityWork');if(!work)return;work.innerHTML=`<div class="panel-header"><div><h3>📐 Sơ đồ lớp học — ngẫu nhiên cân bằng</h3><p>${list.length} học sinh · ${cols} dãy/tổ · mỗi bàn 2 học sinh · ${maxDesks} bàn/dãy</p></div></div><div class="table-container"><table class="data-table"><thead><tr><th>Bàn</th>${Array.from({length:cols},(_,i)=>`<th>Dãy ${i+1} — Tổ ${i+1}</th>`).join('')}</tr></thead><tbody>${html}</tbody></table></div><div class="panel-header" style="margin-top:16px"><div><h3>Nguyên tắc xếp</h3><p>Học sinh được xáo trộn bằng thứ tự ngẫu nhiên, sau đó phân bổ vòng tròn theo các nhóm trình độ để tránh dồn cùng một mức vào một dãy. Hệ thống không tự gán xếp loại nếu dữ liệu thực tế không có.</p></div></div>`}
function install(){const p=ensurePage();if(!p)return;let nav=document.querySelector('.main-menu');if(nav&&!nav.querySelector('[data-page="utilities"]')){const b=document.createElement('button');b.type='button';b.className='menu-item';b.dataset.page='utilities';b.innerHTML='<i class="fa-solid fa-toolbox"></i><span>Tiện ích</span>';const settings=nav.querySelector('[data-page="settings"]');if(settings)nav.insertBefore(b,settings);else nav.appendChild(b)}document.addEventListener('click',e=>{const b=e.target.closest?.('[data-lh-util]');if(!b)return;const k=b.dataset.lhUtil;if(k==='levels')renderLevels();if(k==='seating')seating()},{passive:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();