export function normalizeText(v=""){return String(v??"").replace(/\s+/g," ").trim();}
export function canon(v=""){return normalizeText(v).toLocaleLowerCase("vi").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").replace(/[^a-z0-9]+/g,"");}
export function makeId(p="ID"){return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,10)}`;}
export class Router{constructor(initial="home"){this.current={route:initial,params:{}};this.listeners=[]}onChange(fn){this.listeners.push(fn);return()=>{this.listeners=this.listeners.filter(x=>x!==fn)}}go(route,params={}){this.current={route,params};for(const fn of this.listeners)fn(route,params)}}
export class Events{constructor(){this.map=new Map()}on(name,fn){if(!this.map.has(name))this.map.set(name,[]);this.map.get(name).push(fn);return()=>{const a=this.map.get(name)||[];this.map.set(name,a.filter(x=>x!==fn))}}emit(name,payload){for(const fn of this.map.get(name)||[])fn(payload)}}
const KEY="LH_V2_2026_2027";
export const DATASET={config:{school:"Trường Tiểu học Nghĩa Hành",className:"5A3",schoolYear:"2026–2027",teacher:"Lê Hoàng"},students:[],attendance:[],violations:[],rewards:[],learning:[],progress:[],comments:[],links:{},smasImports:{}};
const SEED_NAMES=[["Nguyễn Bảo An","01/02/2016"],["Phạm Nguyễn Thiên Anh","22/01/2016"],["Nguyễn Ngọc Bích","13/9/2016"],["Lương Bảo Châu","31/01/2016"],["Trần Thị Ngọc Diệp","11/02/2016"],["Võ Thị Huyền Diệu","01/9/2016"],["Phạm Minh Đức","23/8/2016"],["Huỳnh Đặng Quốc Hoàng","19/11/2016"],["Nguyễn Gia Hưng","07/12/2016"],["Tạ Trí Khang","20/8/2016"],["Nguyễn Văn Đăng Khoa","28/3/2016"],["Phạm Đăng Khôi","29/9/2016"],["Ngô Sinh Khởi","01/10/2016"],["Phạm Anh Kiệt","17/7/2016"],["Trần Anh Kiệt","08/3/2016"],["Nguyễn Quỳnh Lam","18/01/2016"],["Trịnh Gia Linh","06/8/2016"],["Phạm Tấn Mạnh","30/5/2016"],["Bùi Nguyễn Hà My","24/01/2016"],["Lương Đỗ Thảo My","19/6/2016"],["Huỳnh Hữu Nam","13/11/2016"],["Bùi Huỳnh Khánh Ngọc","15/4/2016"],["Nguyễn Bùi Bảo Ngọc","07/7/2016"],["Nguyễn Thị Bảo Ngọc","09/01/2016"],["Trịnh Phước Nguyên","11/11/2016"],["Ngô Thiện Nhân","12/10/2016"],["Phạm Lê An Nhiên","21/12/2016"],["Lê Văn Phát","15/02/2016"],["Bùi Văn Phong","04/4/2016"],["Đinh Nguyễn Anh Phong","18/01/2016"],["Nguyễn Văn Phước","02/12/2016"],["Phạm Anh Quân","17/7/2016"],["Đoàn Văn Quý","10/6/2016"],["Lê Hữu Phú Quý","10/9/2016"],["Huỳnh Lê Nhã Quyên","29/10/2016"],["Lê Bá Thụ","14/12/2016"],["Huỳnh Bảo Trâm","10/8/2016"],["Nguyễn Đăng Trường","23/02/2016"],["Võ Tấn Trường","14/12/2016"],["Huỳnh Gia Tuệ","12/3/2016"],["Võ Thanh Vỹ","22/10/2016"],["Huỳnh Ngọc Bảo Yến","30/11/2016"]];
for(const [name,birthDate] of SEED_NAMES)DATASET.students.push({id:makeId("STU"),name,birthDate,gender:"",studentCode:"",status:"active",shareEnabled:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
export class Store{constructor(defaultData){this.data=this.load(defaultData)}load(seed){try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);return this.merge(seed,x)}}catch{}return JSON.parse(JSON.stringify(seed))}merge(seed,x){const d=JSON.parse(JSON.stringify(seed));for(const k of Object.keys(d)){if(x[k]!==undefined)d[k]=x[k]}return d}persist(){localStorage.setItem(KEY,JSON.stringify(this.data))}clear(){localStorage.removeItem(KEY);this.data=JSON.parse(JSON.stringify(DATASET))}ensureLink(studentId){if(!this.data.links)this.data.links={};if(!this.data.links[studentId]){const token=globalThis.crypto?.randomUUID?.().replaceAll("-","").slice(0,18)||Math.random().toString(36).slice(2,20);this.data.links[studentId]={token,url:`${location.origin}${location.pathname}#student=${token}`};this.persist()}return this.data.links[studentId]}}
export function aggregateStudent(data,studentId){const att=data.attendance.filter(r=>r.studentId===studentId);const learning=data.learning.filter(r=>r.studentId===studentId);const groups={GK1:{count:0,subjects:[],records:[]},CK1:{count:0,subjects:[],records:[]},GK2:{count:0,subjects:[],records:[]},CK2:{count:0,subjects:[],records:[]}};for(const r of learning){const g=groups[canonicalStage(r.stage)]||groups.GK1;g.count+=1;g.records.push(r);for(const s of (r.subjects||[]))if(!g.subjects.includes(s))g.subjects.push(s)}return{attendance:{present:att.filter(x=>x.status==="present").length,excused:att.filter(x=>x.status==="excused").length,absent:att.filter(x=>x.status==="absent").length,total:att.length},violations:data.violations.filter(r=>r.studentId===studentId),rewards:data.rewards.filter(r=>r.studentId===studentId),learning:groups,progress:data.progress.filter(r=>r.studentId===studentId),comments:data.comments.filter(r=>r.studentId===studentId),student:data.students.find(s=>s.id===studentId)||null}}
export function canonicalStage(v){const s=canon(v);if(s.includes("giuaiky1")||s.includes("giuaky1")||s==="gk1")return"GK1";if(s.includes("cuoiky1")||s.includes("cuoiky i")||s==="ck1")return"CK1";if(s.includes("giuaiky2")||s.includes("giuaky2")||s==="gk2")return"GK2";if(s.includes("cuoinam")||s.includes("cuoiky2")||s.includes("ck2")||s.includes("cuky2"))return"CK2";return normalizeText(v)||"GK1"}
export function detectHeaderRow(rows=[]){let best={index:-1,score:0};const keys=["họ và tên","họ tên","học sinh","mã học sinh","mã hs","student id","điểm","môn","toán","tiếng việt","phẩm chất","năng lực"];rows.slice(0,30).forEach((row,index)=>{const text=canon((Array.isArray(row)?row:[]).join(" | "));let score=0;for(const k of keys)if(text.includes(canon(k)))score++;if(score>best.score)best={index,score}});return best.index>=0&&best.score>=2?best.index:-1}
function rowToText(row){return Array.isArray(row)?row.map(normalizeText).join(" | "):normalizeText(row)}
function dateVariants(v=""){const s=normalizeText(v);const m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);return m?[`${String(+m[1]).padStart(2,"0")}/${String(+m[2]).padStart(2,"0")}/${m[3]}`,`${+m[1]}/${+m[2]}/${m[3]}`]:[]}
function findStudentIdCandidate(row,headers=[]){const vals=(Array.isArray(row)?row:[]).map(normalizeText);const hs=headers.map(canon);const idx=hs.findIndex(x=>["mahocsinh","mahs","studentid","id","mãhọc sinh"].some(k=>x===canon(k)));return idx>=0?vals[idx]:""}
function findNameCandidate(row,headers=[]){const vals=(Array.isArray(row)?row:[]).map(normalizeText);const hs=headers.map(canon);const idx=hs.findIndex(x=>["hovaten","hoten","hocsinh","họvàtên"].some(k=>x===canon(k)));return idx>=0?vals[idx]:vals.find(v=>v.split(/\s+/).length>=2&&/[a-zA-ZÀ-ỹ]/.test(v))||""}
function matchByStudentId(candidate,roster){const c=canon(candidate);if(!c)return null;return roster.find(s=>canon(s.studentCode)===c)||roster.find(s=>canon(s.id)===c)||null}
function matchByName(name,birth,roster){const n=canon(name);if(!n)return null;const exact=roster.filter(s=>canon(s.name)===n);if(exact.length===1)return{student:exact[0],mode:"name-exact"};const withBirth=exact.filter(s=>!birth||dateVariants(s.birthDate).some(v=>dateVariants(birth).includes(v)));if(withBirth.length===1)return{student:withBirth[0],mode:"name+birthdate"};return null}
export function matchSmAsRecords(source,roster,stage){const safeRoster=Array.isArray(roster)?roster:[];const allSheets=Array.isArray(source?.sheets)?source.sheets:[];const normalizedSheets=allSheets.map(s=>({name:s.name||"Sheet",rows:Array.isArray(s.rows)?s.rows:[]}));const results=[];const conflicts=[];const headersBySheet=new Map();for(const sheet of normalizedSheets){const h=detectHeaderRow(sheet.rows);headersBySheet.set(sheet.name,h>=0&&Array.isArray(sheet.rows[h])?sheet.rows[h]:[]);for(let i=Math.max(0,h);i<sheet.rows.length;i++){const row=sheet.rows[i];if(!Array.isArray(row))continue;const headers=headersBySheet.get(sheet.name)||[];const idCandidate=findStudentIdCandidate(row,headers);const nameCandidate=findNameCandidate(row,headers);let hit=matchByStudentId(idCandidate,safeRoster);let mode=hit?"student-id":"";if(!hit){const m=matchByName(nameCandidate,"",safeRoster);if(m){hit=m.student;mode=m.mode}}if(!hit)continue;results.push({student:hit,studentId:hit.id,raw:row,sheet:sheet.name,rowIndex:i,matchStatus:mode||"matched"})}}
const unique=new Map();for(const x of results){const prior=unique.get(x.studentId);if(prior&&JSON.stringify(prior.raw)!==JSON.stringify(x.raw))conflicts.push({studentId:x.studentId,name:x.student.name,rows:[prior.rowIndex,x.rowIndex],sheets:[prior.sheet,x.sheet]});if(!prior||x.matchStatus==="student-id")unique.set(x.studentId,x)}
const matched=[...unique.values()].map(x=>{const rawText=rowToText(x.raw);const subjects=extractSubjectNames(rawText);return{studentId:x.studentId,name:x.student.name,birthDate:x.student.birthDate,studentCode:x.student.studentCode||"",subjectCount:subjects.length,subjects,raw:x.raw,sheet:x.sheet,rowIndex:x.rowIndex,matchStatus:x.matchStatus}});
return{source:source?.source||"",title:detectImportTitle(normalizedSheets),stage:canonicalStage(stage||source?.title),rowCount:normalizedSheets.reduce((n,s)=>n+s.rows.length,0),headerRows:[...headersBySheet.entries()].map(([sheet,index])=>({sheet,index})),matched,unmatched:safeRoster.filter(s=>!matched.some(m=>m.studentId===s.id)).map(s=>s.name),conflicts,preview:matched.map(x=>({name:x.name,birthDate:x.birthDate,studentCode:x.studentCode,matchStatus:x.matchStatus,subjects:x.subjects.join(", ")}))}}
function extractSubjectNames(text){const list=["Toán","Tiếng Việt","Đạo đức","Lịch sử và Địa lí","Lịch sử","Tiếng Anh","Tin học","Khoa học","Công nghệ","Nghệ thuật","Hoạt động trải nghiệm","Giáo dục thể chất"];const c=canon(text);return list.filter(x=>c.includes(canon(x)))}
function detectImportTitle(sheets){const text=(sheets||[]).slice(0,3).flatMap(s=>s.rows.slice(0,15)).flat().join(" ");return canonicalStage(text)||""}
export async function importFile(file){if(!file||!file.name)throw new Error("Chưa chọn tệp.");const ext=(file.name.split(".").pop()||"").toLowerCase();if(ext==="csv"){const text=await file.text();return{kind:"csv",source:file.name,sheets:[parseCSV(text)]}}if(ext==="xls"||ext==="xlsx"){if(!globalThis.XLSX)throw new Error("Thư viện XLSX chưa sẵn sàng.");const buf=await file.arrayBuffer();const wb=globalThis.XLSX.read(buf,{type:"array"});return{kind:"xlsx",source:file.name,sheets:wb.SheetNames.map(n=>({name:n,rows:globalThis.XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:"",raw:false}))})}}if(ext==="pdf")return await readPDF(file);throw new Error("Định dạng chưa được hỗ trợ. Hãy dùng PDF, XLS, XLSX hoặc CSV.")}
function parseCSV(text){const rows=[];let row=[],cur="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cur+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cur);cur="";}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cur);if(row.some(v=>normalizeText(v)!==""))rows.push(row);row=[];cur="";}else cur+=c;}if(cur!==""||row.length){row.push(cur);if(row.some(v=>normalizeText(v)!==""))rows.push(row)}return{name:"CSV",rows}}
async function readPDF(file){if(!globalThis.pdfjsLib)throw new Error("PDF.js chưa sẵn sàng. Tải lại trang và thử lại.");const buf=await file.arrayBuffer();const pdf=await globalThis.pdfjsLib.getDocument({data:buf}).promise;const pages=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const c=await page.getTextContent();const items=c.items||[];const rows=groupPdfItemsIntoRows(items);pages.push({name:`Page ${p}`,rows})}return{kind:"pdf",source:file.name,sheets:pages}}
function groupPdfItemsIntoRows(items){const buckets=[];for(const item of items){const y=Number(item.transform?.[5]||0);const text=normalizeText(item.str);if(!text)continue;let bucket=buckets.find(b=>Math.abs(b.y-y)<3);if(!bucket){bucket={y,items:[]};buckets.push(bucket)}bucket.items.push({x:Number(item.transform?.[4]||0),text})}buckets.sort((a,b)=>b.y-a.y);return buckets.map(b=>b.items.sort((a,c)=>a.x-c.x).map(x=>x.text).join(" | ")).map(x=>[x])}
export function buildLearningRecord(match,stage,meta={}){return{studentId:match.studentId,stage:canonicalStage(stage),subjects:match.subjects||[],raw:match.raw||[],source:meta.source||"",importedAt:new Date().toISOString(),sheet:match.sheet||"",rowIndex:Number.isFinite(match.rowIndex)?match.rowIndex:null,matchStatus:match.matchStatus||"matched"}}
