export function normalizeText(v=""){return String(v??"").replace(/\s+/g," ").trim();}
export function makeId(p="ID"){return `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,10)}`;}
export class Router{constructor(initial="home"){this.current={route:initial,params:{}};this.listeners=[]}onChange(fn){this.listeners.push(fn)}go(route,params={}){this.current={route,params};for(const fn of this.listeners)fn(route,params)}}
export class Events{constructor(){this.map=new Map()}on(name,fn){if(!this.map.has(name))this.map.set(name,[]);this.map.get(name).push(fn)}emit(name,payload){for(const fn of this.map.get(name)||[])fn(payload)}}
const KEY="LH_V2_2026_2027";
export const DATASET={config:{school:"Trường Tiểu học Nghĩa Hành",className:"5A3",schoolYear:"2026–2027",teacher:"Lê Hoàng"},students:[],attendance:[],violations:[],rewards:[],learning:[],progress:[],comments:[],links:{},smasImports:{}};
const SEED_NAMES=[["Nguyễn Bảo An","01/02/2016"],["Phạm Nguyễn Thiên Anh","22/01/2016"],["Nguyễn Ngọc Bích","13/9/2016"],["Lương Bảo Châu","31/01/2016"],["Trần Thị Ngọc Diệp","11/02/2016"],["Võ Thị Huyền Diệu","01/9/2016"],["Phạm Minh Đức","23/8/2016"],["Huỳnh Đặng Quốc Hoàng","19/11/2016"],["Nguyễn Gia Hưng","07/12/2016"],["Tạ Trí Khang","20/8/2016"],["Nguyễn Văn Đăng Khoa","28/3/2016"],["Phạm Đăng Khôi","29/9/2016"],["Ngô Sinh Khởi","01/10/2016"],["Phạm Anh Kiệt","17/7/2016"],["Trần Anh Kiệt","08/3/2016"],["Nguyễn Quỳnh Lam","18/01/2016"],["Trịnh Gia Linh","06/8/2016"],["Phạm Tấn Mạnh","30/5/2016"],["Bùi Nguyễn Hà My","24/01/2016"],["Lương Đỗ Thảo My","19/6/2016"],["Huỳnh Hữu Nam","13/11/2016"],["Bùi Huỳnh Khánh Ngọc","15/4/2016"],["Nguyễn Bùi Bảo Ngọc","07/7/2016"],["Nguyễn Thị Bảo Ngọc","09/01/2016"],["Trịnh Phước Nguyên","11/11/2016"],["Ngô Thiện Nhân","12/10/2016"],["Phạm Lê An Nhiên","21/12/2016"],["Lê Văn Phát","15/02/2016"],["Bùi Văn Phong","04/4/2016"],["Đinh Nguyễn Anh Phong","18/01/2016"],["Nguyễn Văn Phước","02/12/2016"],["Phạm Anh Quân","17/7/2016"],["Đoàn Văn Quý","10/6/2016"],["Lê Hữu Phú Quý","10/9/2016"],["Huỳnh Lê Nhã Quyên","29/10/2016"],["Lê Bá Thụ","14/12/2016"],["Huỳnh Bảo Trâm","10/8/2016"],["Nguyễn Đăng Trường","23/02/2016"],["Võ Tấn Trường","14/12/2016"],["Huỳnh Gia Tuệ","12/3/2016"],["Võ Thanh Vỹ","22/10/2016"],["Huỳnh Ngọc Bảo Yến","30/11/2016"]];
for(const [name,birthDate] of SEED_NAMES)DATASET.students.push({id:makeId("STU"),name,birthDate,gender:"",studentCode:"",status:"active",shareEnabled:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
export class Store{constructor(defaultData){this.data=this.load(defaultData)}load(seed){try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);return this.merge(seed,x)}}catch{}return JSON.parse(JSON.stringify(seed))}merge(seed,x){const d=JSON.parse(JSON.stringify(seed));for(const k of Object.keys(d)){if(x[k]!==undefined)d[k]=x[k]}return d}persist(){localStorage.setItem(KEY,JSON.stringify(this.data))}clear(){localStorage.removeItem(KEY);this.data=JSON.parse(JSON.stringify(DATASET))}ensureLink(studentId){if(!this.data.links)this.data.links={};if(!this.data.links[studentId]){const token=crypto.randomUUID?.().replaceAll("-","").slice(0,18)||Math.random().toString(36).slice(2,20);this.data.links[studentId]={token,url:`${location.origin}${location.pathname}#student=${token}`}}return this.data.links[studentId]}}
export function aggregateStudent(data,studentId){const att=data.attendance.filter(r=>r.studentId===studentId);const learning=data.learning.filter(r=>r.studentId===studentId);const groups={GK1:{count:0,subjects:[]},CK1:{count:0,subjects:[]},GK2:{count:0,subjects:[]},CK2:{count:0,subjects:[]}};for(const r of learning){const g=groups[r.stage||"GK1"]||groups.GK1;g.count+=1;for(const s of (r.subjects||[]))if(!g.subjects.includes(s))g.subjects.push(s)}return{attendance:{present:att.filter(x=>x.status==="present").length,excused:att.filter(x=>x.status==="excused").length,absent:att.filter(x=>x.status==="absent").length},violations:data.violations.filter(r=>r.studentId===studentId),rewards:data.rewards.filter(r=>r.studentId===studentId),learning:groups,progress:data.progress.filter(r=>r.studentId===studentId),comments:data.comments.filter(r=>r.studentId===studentId)}}
export async function importFile(file){const ext=(file.name.split(".").pop()||"").toLowerCase();if(ext==="csv"){const text=await file.text();return{kind:"csv",source:file.name,sheets:[parseCSV(text)]}}if(ext==="xls"||ext==="xlsx"){if(!window.XLSX)throw new Error("Thư viện XLSX chưa sẵn sàng.");const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:"array"});return{kind:"xlsx",source:file.name,sheets:wb.SheetNames.map(n=>({name:n,rows:XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:""})}))}}if(ext==="pdf")return await readPDF(file);throw new Error("Định dạng chưa được hỗ trợ.")}
function parseCSV(text){return{name:"CSV",rows:text.split(/\r?\n/).map(line=>{let out=[],cur="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"')q=!q;else if(c===","&&!q){out.push(cur);cur=""}else cur+=c}out.push(cur);return out})}}
async function readPDF(file){if(!window.pdfjsLib)throw new Error("PDF.js chưa sẵn sàng. Tải lại trang và thử lại.");const buf=await file.arrayBuffer();const pdf=await window.pdfjsLib.getDocument({data:buf}).promise;let pages=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p);const c=await page.getTextContent();pages.push({name:`Page ${p}`,rows:[c.items.map(x=>x.str).join(" ")]})}return{kind:"pdf",source:file.name,sheets:pages}}
function canon(v){return normalizeText(v).toLocaleLowerCase("vi").normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function extractTitle(rows){const text=rows.slice(0,12).flat().join(" ");const m=text.match(/(GIUA KY 1|GIUA KY I|CUOI KY 1|CUOI KY I|GIUA KY 2|GIUA KY II|CUOI NAM)/i);return m?m[1]:""}
export function matchSmAsRecords(source,roster,stage){const all=source.sheets.flatMap(s=>s.rows||[]);let rowCandidates=[];for(const s of source.sheets){for(const row of s.rows||[]){const joined=Array.isArray(row)?row.map(normalizeText).join(" | "):String(row);const hit=roster.find(st=>canon(joined).includes(canon(st.name))&&(st.birthDate?joined.includes(st.birthDate):true));if(hit)rowCandidates.push({student:hit,raw:Array.isArray(row)?row:[joined]})}const text=(s.rows||[]).flat().join(" ");for(const st of roster)if(canon(text).includes(canon(st.name))&&!rowCandidates.some(x=>x.student.id===st.id))rowCandidates.push({student:st,raw:[text]})}const unique=new Map();for(const x of rowCandidates)unique.set(x.student.id,x);const matched=[...unique.values()].map(x=>{const subjects=[...new Set((x.raw||[]).join(" | ").split("|").map(normalizeText).filter(t=>/^(Toán|Tiếng Việt|Đạo đức|Lịch sử|Tiếng Anh|Tin học|Khoa học|Công nghệ|Nghệ thuật|Hoạt động trải|Giáo dục thể chất)/i.test(t)))];return{studentId:x.student.id,name:x.student.name,birthDate:x.student.birthDate,subjectCount:subjects.length,subjects,raw:x.raw,matchStatus:"Khớp tên + ngữ cảnh"}});return{source:source.source,title:extractTitle(source.sheets[0]?.rows||[]),stage,rowCount:all.length,matched,unmatched:roster.filter(s=>!matched.some(m=>m.studentId===s.id)).map(s=>s.name),conflicts:[],preview:matched.map(x=>({name:x.name,birthDate:x.birthDate,matchStatus:x.matchStatus,subjects:x.subjects.join(", ")})).concat(roster.filter(s=>!matched.some(m=>m.studentId===s.id)).slice(0,10).map(s=>({name:s.name,birthDate:s.birthDate,matchStatus:"Chưa tìm thấy",subjects:""})))};}