/************************************************************
 * LÊ HOÀNG CLASSROOM SYNC — MASTER 7.0
 * AUTHORITATIVE GOOGLE SHEETS EVENT STORE
 ************************************************************/
const CONFIG=Object.freeze({
 SPREADSHEET_ID:'1v9H6dReZiC_fCg6T9ISdfWOy1FN1HJQXXrKsABiCLI4',
 SCHOOL_YEAR:'2026–2027',CLASS_NAME:'5C',EXPECTED_STUDENTS:42,
 VERSION:'MASTER-7.0-AUTHORITATIVE-VERIFIED',
 ROSTER_URL:'https://raw.githubusercontent.com/levanhoangtsth1977-crypto/Quan_li_lop_hoc_thay_le_hoang/master/DANH_SACH_HOC_SINH_5C_2026_2027.json',
 HEADERS:{
  HOC_SINH:['id','name','gender','birthDate','status','parentName','phone','address','note','shareEnabled','createdAt','updatedAt'],
  DIEM_DANH:['id','studentId','date','status','note','createdAt','updatedAt'],
  VI_PHAM:['id','studentId','date','type','level','status','action','note','createdAt','updatedAt'],
  KHEN_THUONG:['id','studentId','date','type','formType','note','createdAt','updatedAt'],
  NHAT_KY:['timestamp','action','sheet','recordId','message']
 }
});
const text_=v=>String(v==null?'':v).trim().replace(/\s+/g,' ');
const ss_=()=>SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID);
function json_(o,e){const cb=text_(e&&e.parameter&&e.parameter.callback),s=JSON.stringify(o);return cb&&/^[A-Za-z_$][\w$\.]*$/.test(cb)?ContentService.createTextOutput(cb+'('+s+');').setMimeType(ContentService.MimeType.JAVASCRIPT):ContentService.createTextOutput(s).setMimeType(ContentService.MimeType.JSON)}
function log_(action,sheet,id,msg){try{const sh=ss_().getSheetByName('NHAT_KY')||ss_().insertSheet('NHAT_KY');const h=CONFIG.HEADERS.NHAT_KY;if(sh.getMaxColumns()<5)sh.insertColumnsAfter(sh.getMaxColumns(),5-sh.getMaxColumns());sh.getRange(1,1,1,5).setValues([h]);sh.appendRow([new Date(),action,sheet||'',id||'',msg||''])}catch(e){}}
function KHOI_TAO_CSDL(){const ss=ss_();Object.keys(CONFIG.HEADERS).forEach(n=>{let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);const h=CONFIG.HEADERS[n];if(sh.getMaxColumns()<h.length)sh.insertColumnsAfter(sh.getMaxColumns(),h.length-sh.getMaxColumns());sh.getRange(1,1,1,h.length).setValues([h])});SpreadsheetApp.flush();return{ok:true,spreadsheetId:ss.getId(),spreadsheetName:ss.getName(),tabs:Object.keys(CONFIG.HEADERS)}}
function studentSheet_(){const sh=ss_().getSheetByName('HOC_SINH');if(!sh)throw Error('Không tìm thấy HOC_SINH');if(sh.getMaxColumns()<12)sh.insertColumnsAfter(sh.getMaxColumns(),12-sh.getMaxColumns());sh.getRange(1,1,1,12).setValues([CONFIG.HEADERS.HOC_SINH]);return sh}
function readStudents_(){const sh=studentSheet_(),n=sh.getLastRow();if(n<2)return[];return sh.getRange(2,1,n-1,12).getValues().map(r=>({id:text_(r[0]),name:text_(r[1]),gender:text_(r[2]),birthDate:r[3],status:text_(r[4])||'active',parentName:text_(r[5]),phone:text_(r[6]),address:text_(r[7]),note:text_(r[8]),shareEnabled:String(r[9]).toUpperCase()!=='FALSE',createdAt:r[10],updatedAt:r[11]})).filter(s=>s.id&&s.name)}
function restoreMasterStudents_(){const sh=studentSheet_(),old=readStudents_();if(old.length)return{ok:true,restored:false,count:old.length,expected:42,source:'GOOGLE_SHEETS'};const res=UrlFetchApp.fetch(CONFIG.ROSTER_URL,{muteHttpExceptions:true,followRedirects:true});if(res.getResponseCode()!==200)throw Error('MASTER roster HTTP '+res.getResponseCode());const src=JSON.parse(res.getContentText()),list=Array.isArray(src)?src:(src.students||src.HOC_SINH||[]);if(list.length!==42)throw Error('MASTER roster phải có 42 HS, hiện có '+list.length);const now=new Date(),rows=list.map((s,i)=>[text_(s.id)||('STU_5C_2026_'+String(i+1).padStart(3,'0')),text_(s.name||s.studentName),text_(s.gender),s.birthDate||'',text_(s.status)||'active',text_(s.parentName),text_(s.phone),text_(s.address),text_(s.note),s.shareEnabled!==false,s.createdAt||now,now]);if(sh.getMaxRows()<43)sh.insertRowsAfter(sh.getMaxRows(),43-sh.getMaxRows());sh.getRange(2,1,42,12).setValues(rows);SpreadsheetApp.flush();log_('MASTER_ROSTER_RESTORE','HOC_SINH','','Khôi phục 42 học sinh');return{ok:true,restored:true,count:42,expected:42,source:'GITHUB_MASTER_ROSTER',version:CONFIG.VERSION}}
function eventSheet_(tab){const h=CONFIG.HEADERS[tab];if(!h)throw Error('Tab sự kiện không hợp lệ: '+tab);const sh=ss_().getSheetByName(tab)||ss_().insertSheet(tab);if(sh.getMaxColumns()<h.length)sh.insertColumnsAfter(sh.getMaxColumns(),h.length-sh.getMaxColumns());sh.getRange(1,1,1,h.length).setValues([h]);return sh}
function eventRead_(tab){const sh=eventSheet_(tab),h=CONFIG.HEADERS[tab],n=sh.getLastRow();if(n<2)return[];return sh.getRange(2,1,n-1,h.length).getValues().map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]);return o}).filter(o=>text_(o.id)&&text_(o.studentId)).filter(o=>tab!=='DIEM_DANH'||!/^present|có mặt|co mat$/i.test(text_(o.status)))}
function cleanRows_(sh,h){const n=sh.getLastRow();if(n>1)sh.getRange(2,1,n-1,h.length).clearContent()}
function syncEvents_(payload){const rec=payload&&payload.records||{};const out={ok:true,mode:'AUTHORITATIVE_REPLACE',version:CONFIG.VERSION};['DIEM_DANH','VI_PHAM','KHEN_THUONG'].forEach(tab=>{const sh=eventSheet_(tab),h=CONFIG.HEADERS[tab],incoming=Array.isArray(rec[tab])?rec[tab]:[];const rows=incoming.filter(r=>r&&text_(r.studentId)&&!(tab==='DIEM_DANH'&&/^present|có mặt|co mat$/i.test(text_(r.status)))).map(r=>h.map(k=>k==='createdAt'?(r[k]||new Date()):k==='updatedAt'?new Date():(r[k]??'')));cleanRows_(sh,h);if(rows.length){if(sh.getMaxRows()<rows.length+1)sh.insertRowsAfter(sh.getMaxRows(),rows.length+1-sh.getMaxRows());sh.getRange(2,1,rows.length,h.length).setValues(rows)}SpreadsheetApp.flush();out[tab]={received:incoming.length,stored:rows.length};log_('AUTHORITATIVE_REPLACE',tab,'','received='+incoming.length+';stored='+rows.length)});return out}
function getEvents_(){return{ok:true,mode:'AUTHORITATIVE_REPLACE',DIEM_DANH:eventRead_('DIEM_DANH'),VI_PHAM:eventRead_('VI_PHAM'),KHEN_THUONG:eventRead_('KHEN_THUONG'),source:'GOOGLE_SHEETS',version:CONFIG.VERSION}}
function getAll_(){const students=readStudents_();return{ok:true,HOC_SINH:students,DIEM_DANH:eventRead_('DIEM_DANH'),VI_PHAM:eventRead_('VI_PHAM'),KHEN_THUONG:eventRead_('KHEN_THUONG'),source:'GOOGLE_SHEETS',version:CONFIG.VERSION}}
function doGet(e){const a=text_(e&&e.parameter&&e.parameter.action).toLowerCase()||'ping';try{KHOI_TAO_CSDL();if(a==='ping'){let s=readStudents_(),b=null;if(!s.length){b=restoreMasterStudents_();s=readStudents_()}return json_({ok:true,service:'LE_HOANG_CLASSROOM_SYNC',version:CONFIG.VERSION,spreadsheetId:CONFIG.SPREADSHEET_ID,spreadsheetName:ss_().getName(),tabs:ss_().getSheets().map(s=>s.getName()),students:s.length,expectedStudents:42,complete:s.length===42,bootstrap:b},e)}if(a==='get_students'||a==='getstudents'){let s=readStudents_(),b=null;if(!s.length){b=restoreMasterStudents_();s=readStudents_()}return json_({ok:true,count:s.length,expected:42,complete:s.length===42,students:s,bootstrap:b,source:'GOOGLE_SHEETS_HOC_SINH',version:CONFIG.VERSION},e)}if(a==='get_events'||a==='get_records')return json_(getEvents_(),e);if(a==='get_all')return json_(getAll_(),e);if(a==='restore_master_students'||a==='repair_students')return json_(restoreMasterStudents_(),e);return json_({ok:false,error:'Unknown action: '+a,version:CONFIG.VERSION},e)}catch(err){log_('ERROR','','',String(err.message||err));return json_({ok:false,error:String(err.message||err),version:CONFIG.VERSION},e)}}
function doPost(e){let body={};try{body=e&&e.postData&&e.postData.contents?JSON.parse(e.postData.contents):(e&&e.parameter&&e.parameter.payload?JSON.parse(e.parameter.payload):e&&e.parameter?e.parameter:{})}catch(err){return json_({ok:false,error:'Payload JSON không hợp lệ',version:CONFIG.VERSION},e)}try{const a=text_(body.action).toLowerCase();if(a==='sync_events'||a==='sync_records')return json_(syncEvents_(body),e);if(a==='restore_master_students'||a==='repair_students')return json_(restoreMasterStudents_(),e);return json_({ok:false,error:'Unknown POST action: '+a,version:CONFIG.VERSION},e)}catch(err){log_('ERROR','','',String(err.message||err));return json_({ok:false,error:String(err.message||err),version:CONFIG.VERSION},e)}}
function BOOTSTRAP_CSDL_A_TO_Z(){KHOI_TAO_CSDL();let s=readStudents_(),b=null;if(!s.length)b=restoreMasterStudents_();const ev=getEvents_();return{ok:true,version:CONFIG.VERSION,students:readStudents_().length,expectedStudents:42,attendance:ev.DIEM_DANH.length,violations:ev.VI_PHAM.length,rewards:ev.KHEN_THUONG.length,bootstrap:b}}
function testConnection(){const b=BOOTSTRAP_CSDL_A_TO_Z();Logger.log(JSON.stringify(b));return b}
