/**
 * QUẢN LÝ LỚP HỌC THẦY LÊ HOÀNG
 * GOOGLE SHEETS SYNC API — MASTER 3.5 — VERIFIED EVENT WRITE
 * CSDL CHÍNH: Google Sheet 1v9H6dReZiC_fCg6T9ISdfWOy1FN1HJQXXrKsABiCLI4
 * HOC_SINH giữ nguyên đúng 12 cột; không xóa/dồn/đổi ID tự động.
 */
const CONFIG=Object.freeze({SPREADSHEET_ID:'1v9H6dReZiC_fCg6T9ISdfWOy1FN1HJQXXrKsABiCLI4',SCHOOL_YEAR:'2026–2027',CLASS_NAME:'5C',EXPECTED_STUDENTS:42,VERSION:'MASTER-3.5-VERIFIED-EVENT-WRITE',TABS:['HOC_SINH','DIEM_DANH','VI_PHAM','KHEN_THUONG','HOC_TAP','TIEN_BO','NHAN_XET','LINK_HOC_SINH','CAU_HINH','NHAT_KY'],HEADERS:{HOC_SINH:['id','name','gender','birthDate','status','parentName','phone','address','note','shareEnabled','createdAt','updatedAt'],DIEM_DANH:['id','studentId','date','status','note','createdAt','updatedAt'],VI_PHAM:['id','studentId','date','type','level','status','action','note','createdAt','updatedAt'],KHEN_THUONG:['id','studentId','date','type','formType','note','createdAt','updatedAt'],HOC_TAP:['id','studentId','date','subject','result','level','note','createdAt','updatedAt'],TIEN_BO:['id','studentId','date','category','level','score','note','createdAt','updatedAt'],NHAN_XET:['id','studentId','date','subject','content','level','createdAt','updatedAt'],LINK_HOC_SINH:['studentId','studentCode','studentName','studentUrl','enabled','createdAt','updatedAt'],CAU_HINH:['Key','Value','UpdatedAt'],NHAT_KY:['timestamp','action','sheet','recordId','message']}});
function getSpreadsheet_(){return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID)}
function text_(v){return String(v??'').trim().replace(/\s+/g,' ')}
function key_(v){return text_(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9]/g,'')}
function dateKey_(v){if(v instanceof Date&&!isNaN(v.getTime()))return Utilities.formatDate(v,Session.getScriptTimeZone()||'Asia/Ho_Chi_Minh','ddMMyyyy');const s=text_(v);if(!s)return'';let m=s.match(/^(\d{4})[-\/](\d{1,2})[-\/](\d{1,2})/);if(m)return m[3].padStart(2,'0')+m[2].padStart(2,'0')+m[1];m=s.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})/);if(m)return m[1].padStart(2,'0')+m[2].padStart(2,'0')+m[3];return s.replace(/\D/g,'')}
function identityKey_(s){return key_(s.name)+'|'+dateKey_(s.birthDate)+'|'+key_(s.gender)}
function isCanonicalId_(id){return /^STU_5C_2026_\d{3,4}$/i.test(text_(id))}
function preferred_(a,b){if(!a)return b;if(!b)return a;if(isCanonicalId_(b.id)&&!isCanonicalId_(a.id))return b;if(isCanonicalId_(a.id)&&!isCanonicalId_(b.id))return a;return Number(a.row||999999)<=Number(b.row||999999)?a:b}
function json_(obj,e){const cb=text_(e&&e.parameter&&e.parameter.callback);const body=JSON.stringify(obj);if(cb&&/^[A-Za-z_$][\w$\.]*$/.test(cb))return ContentService.createTextOutput(cb+'('+body+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(body).setMimeType(ContentService.MimeType.JSON)}
function ensureEventSheet_(name){const h=CONFIG.HEADERS[name];if(!h)throw new Error('Sheet không được phép: '+name);const ss=getSpreadsheet_();let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getMaxColumns()<h.length)sh.insertColumnsAfter(sh.getMaxColumns(),h.length-sh.getMaxColumns());const current=h.map((_,i)=>text_(sh.getRange(1,i+1).getValue()));const blank=current.every(v=>!v);if(blank)sh.getRange(1,1,1,h.length).setValues([h]);else if(!h.every((x,i)=>current[i]===x))throw new Error('Header '+name+' không đúng schema. API không tự đổi dữ liệu hiện có.');return sh}
function log_(action,sheet,recordId,message){try{const sh=ensureEventSheet_('NHAT_KY');sh.appendRow([new Date(),action,sheet,recordId,message])}catch(_) {}}
function headerOk_(sh,name){const h=CONFIG.HEADERS[name];if(!h||sh.getMaxColumns()<h.length)return false;return h.every((x,i)=>text_(sh.getRange(1,i+1).getValue())===x)}
function readPhysicalStudents_(){const sh=getSpreadsheet_().getSheetByName('HOC_SINH');if(!sh)throw new Error('Không tìm thấy SHEET HOC_SINH.');if(!headerOk_(sh,'HOC_SINH'))throw new Error('Header HOC_SINH không đúng schema. API không tự sửa.');const last=sh.getLastRow();if(last<2)return[];const h=CONFIG.HEADERS.HOC_SINH,w=h.length,values=sh.getRange(2,1,last-1,w).getValues();return values.map((r,i)=>{const s={};h.forEach((k,j)=>s[k]=r[j]);s.id=text_(s.id);s.name=text_(s.name);s.gender=text_(s.gender);s.status=text_(s.status)||'active';s.shareEnabled=!(s.shareEnabled===false||String(s.shareEnabled).toUpperCase()==='FALSE');s.row=i+2;return s}).filter(s=>s.id&&s.name)}
function dedupeLogicalStudents_(physical){const byIdentity=new Map(),duplicates=[];physical.forEach(s=>{const k=identityKey_(s);if(!k||k==='||')return;const current=byIdentity.get(k);if(!current){byIdentity.set(k,s);return}const keep=preferred_(current,s),drop=keep===current?s:current;byIdentity.set(k,keep);duplicates.push({identity:k,keptId:keep.id,droppedId:drop.id,keptRow:keep.row,droppedRow:drop.row,name:keep.name})});return{logical:Array.from(byIdentity.values()).sort((a,b)=>key_(a.name).localeCompare(key_(b.name),'vi')||a.row-b.row),duplicates}}
function readStudents_(){const physical=readPhysicalStudents_(),d=dedupeLogicalStudents_(physical);return{ok:true,count:d.logical.length,physicalCount:physical.length,duplicateCount:d.duplicates.length,students:d.logical,duplicates:d.duplicates,source:'HOC_SINH_SAFE_IDENTITY',version:CONFIG.VERSION}}
function readRecords_(sheet){const sh=ensureEventSheet_(sheet),h=CONFIG.HEADERS[sheet],last=sh.getLastRow();if(last<2)return[];return sh.getRange(2,1,last-1,h.length).getValues().map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]);return o}).filter(r=>text_(r.id))}
function validateEventRecord_(sheet,record){if(!CONFIG.HEADERS[sheet])throw new Error('Sheet không được phép: '+sheet);const r=record||{};const id=text_(r.id);const studentId=text_(r.studentId);if(!id)throw new Error(sheet+': Record thiếu id.');if(!studentId)throw new Error(sheet+': Record thiếu studentId.');const students=readPhysicalStudents_();if(!students.some(s=>s.id===studentId))throw new Error(sheet+': studentId không tồn tại trong HOC_SINH: '+studentId);return r}
function saveEvent_(sheet,record){const h=CONFIG.HEADERS[sheet];const r=validateEventRecord_(sheet,record);const sh=ensureEventSheet_(sheet);const id=text_(r.id);const last=sh.getLastRow(),values=last<2?[]:sh.getRange(2,1,last-1,h.length).getValues();let row=-1;for(let i=0;i<values.length;i++)if(text_(values[i][0])===id){row=i+2;break}const out=h.map(k=>r[k]??'');if(row<0){sh.getRange(sh.getLastRow()+1,1,1,h.length).setValues([out]);row=sh.getLastRow()}else sh.getRange(row,1,1,h.length).setValues([out]);SpreadsheetApp.flush();log_('SAVE_EVENT',sheet,id,'verified-write');return{ok:true,stored:true,verifiedWrite:true,sheet,id,row,version:CONFIG.VERSION}}
function getAll_(){const s=readStudents_();return{ok:true,version:CONFIG.VERSION,HOC_SINH:s.students,DIEM_DANH:readRecords_('DIEM_DANH'),VI_PHAM:readRecords_('VI_PHAM'),KHEN_THUONG:readRecords_('KHEN_THUONG'),HOC_TAP:readRecords_('HOC_TAP'),TIEN_BO:readRecords_('TIEN_BO'),NHAN_XET:readRecords_('NHAN_XET'),meta:{studentCount:s.count,physicalStudentCount:s.physicalCount,duplicateStudentCount:s.duplicateCount}}}
function auditDuplicates_(){const s=readStudents_();return{ok:true,physicalCount:s.physicalCount,logicalCount:s.count,duplicateCount:s.duplicateCount,duplicates:s.duplicates,policy:'READ_ONLY_NO_DELETE'}}
function parseJson_(v){try{return JSON.parse(v||'{}')}catch(e){throw new Error('Payload JSON không hợp lệ.')}}
function doGet(e){const action=text_(e&&e.parameter&&e.parameter.action).toLowerCase()||'ping';try{if(action==='ping')return json_({ok:true,service:'LE_HOANG_CLASSROOM_SYNC',version:CONFIG.VERSION,spreadsheetId:CONFIG.SPREADSHEET_ID,className:CONFIG.CLASS_NAME},e);if(['get_students','getstudents','getstudentslist','students','roster','get_roster'].includes(action))return json_(readStudents_(),e);if(['get_all','all','bootstrap'].includes(action))return json_(getAll_(),e);if(['get_events','events'].includes(action))return json_({ok:true,version:CONFIG.VERSION,DIEM_DANH:readRecords_('DIEM_DANH'),VI_PHAM:readRecords_('VI_PHAM'),KHEN_THUONG:readRecords_('KHEN_THUONG')},e);if(action==='save_event'){const payload=parseJson_(e.parameter.payload);return json_(saveEvent_(payload.sheet,payload.record),e)}if(action==='audit_duplicates')return json_(auditDuplicates_(),e);return json_({ok:false,error:'Unknown action',supportedActions:['ping','get_students','students','roster','get_all','get_events','save_event','audit_duplicates'],version:CONFIG.VERSION},e)}catch(err){return json_({ok:false,error:String(err&&err.message||err),version:CONFIG.VERSION},e)}}
function doPost(e){try{const p=parseJson_(e&&e.postData&&e.postData.contents);const action=text_(p.action).toLowerCase();if(action==='save_event')return json_(saveEvent_(p.sheet,p.record),e);if(action==='get_students')return json_(readStudents_(),e);if(action==='get_all')return json_(getAll_(),e);return json_({ok:false,error:'Unknown POST action',version:CONFIG.VERSION},e)}catch(err){return json_({ok:false,error:String(err&&err.message||err),version:CONFIG.VERSION},e)}}
function testApi(){const s=readStudents_();return{ok:true,version:CONFIG.VERSION,spreadsheetId:CONFIG.SPREADSHEET_ID,className:CONFIG.CLASS_NAME,expectedStudents:CONFIG.EXPECTED_STUDENTS,physicalCount:s.physicalCount,logicalCount:s.count,duplicateCount:s.duplicateCount,students:s.students.map(x=>({id:x.id,name:x.name})),timestamp:new Date().toISOString()}}
