/* QUẢN LÝ LỚP HỌC THẦY LÊ HOÀNG — GOOGLE APPS SCRIPT MASTER 7.0 */
const CONFIG={SPREADSHEET_ID:'1v9H6dReZiC_fCg6T9ISdfWOy1FN1HJQXXrKsABiCLI4',SCHOOL_YEAR:'2026–2027',CLASS_NAME:'5C',EXPECTED_STUDENTS:42,VERSION:'MASTER-7.0-VIETNAMESE-EVENT-DATA',TABS:['HOC_SINH','DIEM_DANH','VI_PHAM','KHEN_THUONG','HOC_TAP','TIEN_BO','NHAN_XET','LINK_HOC_SINH','CAU_HINH','NHAT_KY'],HEADERS:{HOC_SINH:['id','name','gender','birthDate','status','parentName','phone','address','note','shareEnabled','createdAt','updatedAt'],DIEM_DANH:['id','studentName','studentId','date','status','note','createdAt','updatedAt'],VI_PHAM:['id','studentName','studentId','date','type','level','status','action','note','createdAt','updatedAt'],KHEN_THUONG:['id','studentName','studentId','date','type','formType','note','createdAt','updatedAt'],HOC_TAP:['id','studentName','studentId','date','subject','result','level','note','createdAt','updatedAt'],TIEN_BO:['id','studentName','studentId','date','category','level','score','note','createdAt','updatedAt'],NHAN_XET:['id','studentName','studentId','date','subject','content','level','createdAt','updatedAt'],LINK_HOC_SINH:['studentId','studentCode','studentName','studentUrl','enabled','createdAt','updatedAt'],CAU_HINH:['Key','Value','UpdatedAt'],NHAT_KY:['timestamp','action','sheet','recordId','message']}};
const OLD_HEADERS={DIEM_DANH:['id','studentId','date','status','note','createdAt','updatedAt'],VI_PHAM:['id','studentId','date','type','level','status','action','note','createdAt','updatedAt'],KHEN_THUONG:['id','studentId','date','type','formType','note','createdAt','updatedAt'],HOC_TAP:['id','studentId','date','subject','result','level','note','createdAt','updatedAt'],TIEN_BO:['id','studentId','date','category','level','score','note','createdAt','updatedAt'],NHAN_XET:['id','studentId','date','subject','content','level','createdAt','updatedAt']};
function getSpreadsheet_(){return SpreadsheetApp.openById(CONFIG.SPREADSHEET_ID)}
function text_(v){return String(v??'').trim().replace(/\s+/g,' ')}
function key_(v){return text_(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9]/g,'')}
function json_(obj,e){const cb=text_(e&&e.parameter&&e.parameter.callback);const body=JSON.stringify(obj);if(cb&&/^[A-Za-z_$][\w$\.]*$/.test(cb))return ContentService.createTextOutput(cb+'('+body+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(body).setMimeType(ContentService.MimeType.JSON)}
function readPhysicalStudents_(){const sh=getSpreadsheet_().getSheetByName('HOC_SINH');if(!sh)throw Error('Không tìm thấy SHEET HOC_SINH.');const h=CONFIG.HEADERS.HOC_SINH;const cur=h.map((_,i)=>text_(sh.getRange(1,i+1).getValue()));if(!h.every((x,i)=>cur[i]===x))throw Error('Header HOC_SINH không đúng schema.');const last=sh.getLastRow();if(last<2)return[];return sh.getRange(2,1,last-1,h.length).getValues().map((r,i)=>{const s={};h.forEach((k,j)=>s[k]=r[j]);s.id=text_(s.id);s.name=text_(s.name);s.gender=text_(s.gender);s.status=text_(s.status)||'active';s.row=i+2;return s}).filter(s=>s.id&&s.name)}
function studentMap_(){const m={};readPhysicalStudents_().forEach(s=>m[text_(s.id)]=s.name);return m}
function translate_(sheet,field,value){const v=text_(value);const maps={DIEM_DANH:{status:{present:'Có mặt',excused:'Có phép',absent:'Không phép'}},KHEN_THUONG:{type:{'good-deed':'Việc tốt',learning:'Học tập',achievement:'Thành tích'},formType:{praise:'Tuyên dương',certificate:'Giấy khen',gift:'Phần thưởng'}},VI_PHAM:{type:{late:'Đi học muộn','late-school':'Đi học muộn',homework:'Chưa hoàn thành bài',behavior:'Hành vi chưa phù hợp',uniform:'Trang phục',other:'Khác'},level:{low:'Nhẹ',medium:'Trung bình',high:'Nặng'},status:{open:'Đang theo dõi',resolved:'Đã xử lý'},action:{reminder:'Nhắc nhở',discussion:'Trao đổi',support:'Hỗ trợ',other:'Khác'}},HOC_TAP:{level:{M1:'Nhận biết',M2:'Thông hiểu',M3:'Vận dụng'}},TIEN_BO:{level:{M1:'Cần cố gắng',M2:'Đạt',M3:'Tốt'}}};return maps[sheet]?.[field]?.[v]||v}
function normalizeRecordForOutput_(sheet,r){const o={...r};['status','type','level','action','formType'].forEach(k=>{if(o[k]!==undefined)o[k]=translate_(sheet,k,o[k])});return o}
function migrateEventSheet_(sheet){const sh=getSpreadsheet_().getSheetByName(sheet);if(!sh)return;const old=OLD_HEADERS[sheet],neu=CONFIG.HEADERS[sheet],cur=neu.map((_,i)=>text_(sh.getRange(1,i+1).getValue()));if(neu.every((x,i)=>cur[i]===x))return;if(!old.every((x,i)=>cur[i]===x))throw Error('Header '+sheet+' không đúng schema cũ/mới.');const last=sh.getLastRow();sh.insertColumnAfter(1);sh.getRange(1,1,1,neu.length).setValues([neu]);if(last>=2){const oldValues=sh.getRange(2,1,last-1,old.length).getValues();const names=studentMap_();const out=oldValues.map(r=>{const sid=text_(r[1]);return [r[0],names[sid]||'',sid,r[2],r[3],r[4],r[5],r[6]]}).map((r)=>{if(sheet==='VI_PHAM')return [r[0],r[1],r[2],r[3],r[4],r[5],r[6],r[7],oldValues.find(x=>text_(x[0])===text_(r[0]))?.[7]||'',oldValues.find(x=>text_(x[0])===text_(r[0]))?.[8]||'',oldValues.find(x=>text_(x[0])===text_(r[0]))?.[9]||''];if(sheet==='KHEN_THUONG')return [r[0],r[1],r[2],r[3],r[4],r[5],r[6],oldValues.find(x=>text_(x[0])===text_(r[0]))?.[6]||'',oldValues.find(x=>text_(x[0])===text_(r[0]))?.[7]||''];if(sheet==='HOC_TAP')return [r[0],r[1],r[2],r[3],r[4],r[5],r[6],oldValues.find(x=>text_(x[0])===text_(r[0]))?.[6]||'',oldValues.find(x=>text_(x[0])===text_(r[0]))?.[7]||''];if(sheet==='TIEN_BO')return [r[0],r[1],r[2],r[3],r[4],r[5],r[6],oldValues.find(x=>text_(x[0])===text_(r[0]))?.[6]||'',oldValues.find(x=>text_(x[0])===text_(r[0]))?.[7]||'',oldValues.find(x=>text_(x[0])===text_(r[0]))?.[8]||''];return [r[0],r[1],r[2],r[3],r[4],r[5],r[6],r[7],r[8]||''];});sh.getRange(2,1,last-1,neu.length).setValues(out)}}
function ensureEventSheet_(sheet){if(!CONFIG.HEADERS[sheet])throw Error('Sheet không được phép: '+sheet);migrateEventSheet_(sheet);const sh=getSpreadsheet_().getSheetByName(sheet)||getSpreadsheet_().insertSheet(sheet);const h=CONFIG.HEADERS[sheet];if(sh.getMaxColumns()<h.length)sh.insertColumnsAfter(sh.getMaxColumns(),h.length-sh.length);const cur=h.map((_,i)=>text_(sh.getRange(1,i+1).getValue()));if(cur.every(v=>!v))sh.getRange(1,1,1,h.length).setValues([h]);else if(!h.every((x,i)=>cur[i]===x))throw Error('Header '+sheet+' không đúng schema.');return sh}
function readRecords_(sheet){const sh=ensureEventSheet_(sheet),h=CONFIG.HEADERS[sheet],last=sh.getLastRow();if(last<2)return[];return sh.getRange(2,1,last-1,h.length).getValues().map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]);return normalizeRecordForOutput_(sheet,o)}).filter(r=>text_(r.id))}
function validateEventRecord_(sheet,r){if(!CONFIG.HEADERS[sheet])throw Error('Sheet không được phép: '+sheet);const id=text_(r.id),sid=text_(r.studentId);if(!id)throw Error(sheet+': thiếu id.');if(!sid)throw Error(sheet+': thiếu studentId.');const s=readPhysicalStudents_().find(x=>text_(x.id)===sid);if(!s)throw Error(sheet+': studentId không tồn tại: '+sid);r.studentName=text_(r.studentName)||s.name;r.studentId=sid;return r}
function saveEvent_(sheet,record){const h=CONFIG.HEADERS[sheet],r=validateEventRecord_(sheet,{...(record||{})}),sh=ensureEventSheet_(sheet),id=text_(r.id);const last=sh.getLastRow();const vals=last<2?[]:sh.getRange(2,1,last-1,h.length).getValues();let row=-1;for(let i=0;i<vals.length;i++)if(text_(vals[i][0])===id){row=i+2;break}const out=h.map(k=>r[k]??'');if(row<0){row=sh.getLastRow()+1;sh.getRange(row,1,1,h.length).setValues([out])}else sh.getRange(row,1,1,h.length).setValues([out]);SpreadsheetApp.flush();log_('SAVE_EVENT',sheet,id,'verified-write');return{ok:true,stored:true,saved:true,verifiedWrite:true,sheet,id,row,version:CONFIG.VERSION}}
function deleteEvent_(sheet,id){sheet=text_(sheet).toUpperCase();if(!['DIEM_DANH','VI_PHAM','KHEN_THUONG','HOC_TAP'].includes(sheet))throw Error('Không được phép xóa tab này.');const rid=text_(id);if(!rid)throw Error('Thiếu recordId.');const sh=ensureEventSheet_(sheet),last=sh.getLastRow();if(last<2)return{ok:false,deleted:false,error:'Không có dữ liệu để xóa.',sheet,id:rid};const ids=sh.getRange(2,1,last-1,1).getValues();let row=-1;for(let i=0;i<ids.length;i++)if(text_(ids[i][0])===rid){row=i+2;break}if(row<0)return{ok:false,deleted:false,error:'Không tìm thấy lượt có ID: '+rid+' trong '+sheet,sheet,id:rid};sh.deleteRow(row);SpreadsheetApp.flush();return{ok:true,deleted:true,rowDeleted:true,sheet,id:rid,row,version:CONFIG.VERSION}}
function deleteAllEvents_(sheet){sheet=text_(sheet).toUpperCase();if(!['VI_PHAM','KHEN_THUONG'].includes(sheet))throw Error('Chỉ xóa tất cả ở VI_PHAM/KHEN_THUONG.');const sh=ensureEventSheet_(sheet),n=Math.max(0,sh.getLastRow()-1);if(n)sh.getRange(2,1,n,CONFIG.HEADERS[sheet].length).clearContent();SpreadsheetApp.flush();return{ok:true,deleted:true,deletedCount:n,sheet,version:CONFIG.VERSION}}
function readStudents_(){const a=readPhysicalStudents_();return{ok:true,count:a.length,physicalCount:a.length,duplicateCount:0,students:a,source:'HOC_SINH',version:CONFIG.VERSION}}
function log_(action,sheet,recordId,message){try{const sh=ensureEventSheet_('NHAT_KY');sh.appendRow([new Date(),action,sheet,recordId,message])}catch(_) {}}
function getAll_(){return{ok:true,version:CONFIG.VERSION,HOC_SINH:readStudents_().students,DIEM_DANH:readRecords_('DIEM_DANH'),VI_PHAM:readRecords_('VI_PHAM'),KHEN_THUONG:readRecords_('KHEN_THUONG'),HOC_TAP:readRecords_('HOC_TAP'),TIEN_BO:readRecords_('TIEN_BO'),NHAN_XET:readRecords_('NHAN_XET')}}
function parseJson_(v){try{return JSON.parse(v||'{}')}catch(e){throw Error('Payload JSON không hợp lệ.')}}
function doGet(e){const a=text_(e?.parameter?.action).toLowerCase()||'ping';try{if(a==='ping')return json_({ok:true,service:'LE_HOANG_CLASSROOM_SYNC',version:CONFIG.VERSION,spreadsheetId:CONFIG.SPREADSHEET_ID,className:CONFIG.CLASS_NAME},e);if(['get_students','students','roster','get_roster'].includes(a))return json_(readStudents_(),e);if(['get_all','all','bootstrap'].includes(a))return json_(getAll_(),e);if(['get_events','events'].includes(a))return json_({ok:true,version:CONFIG.VERSION,DIEM_DANH:readRecords_('DIEM_DANH'),VI_PHAM:readRecords_('VI_PHAM'),KHEN_THUONG:readRecords_('KHEN_THUONG')},e);if(a==='save_event'){const p=parseJson_(e.parameter.payload||e.parameter.record);return json_(saveEvent_(p.sheet,p.record),e)}if(['delete_event','delete_violation','deleteviolation','remove_violation'].includes(a))return json_(deleteEvent_(e.parameter.sheet||'VI_PHAM',e.parameter.id||e.parameter.recordId||e.parameter.eventId),e);if(['delete_reward','deletereward','remove_reward'].includes(a))return json_(deleteEvent_('KHEN_THUONG',e.parameter.id||e.parameter.recordId||e.parameter.eventId),e);if(['delete_all_events','delete_all','clear_events','clear_all_events'].includes(a))return json_(deleteAllEvents_(e.parameter.sheet),e);return json_({ok:false,error:'Unknown action',version:CONFIG.VERSION},e)}catch(err){return json_({ok:false,error:String(err?.message||err),version:CONFIG.VERSION},e)}}
function doPost(e){try{const p=parseJson_(e?.postData?.contents||e?.parameter?.payload||'{}'),a=text_(p.action).toLowerCase();if(a==='save_event')return json_(saveEvent_(p.sheet,p.record),e);if(['delete_event','delete_violation','deleteviolation','remove_violation'].includes(a))return json_(deleteEvent_(p.sheet||'VI_PHAM',p.id||p.recordId||p.eventId),e);if(['delete_reward','deletereward','remove_reward'].includes(a))return json_(deleteEvent_('KHEN_THUONG',p.id||p.recordId||p.eventId),e);if(['delete_all_events','delete_all','clear_events','clear_all_events'].includes(a))return json_(deleteAllEvents_(p.sheet),e);if(a==='get_events')return json_({ok:true,DIEM_DANH:readRecords_('DIEM_DANH'),VI_PHAM:readRecords_('VI_PHAM'),KHEN_THUONG:readRecords_('KHEN_THUONG')},e);return json_({ok:false,error:'Unknown POST action',version:CONFIG.VERSION},e)}catch(err){return json_({ok:false,error:String(err?.message||err),version:CONFIG.VERSION},e)}}
function migrateAllEventSheets(){['DIEM_DANH','VI_PHAM','KHEN_THUONG','HOC_TAP','TIEN_BO','NHAN_XET'].forEach(migrateEventSheet_);SpreadsheetApp.flush();return{ok:true,version:CONFIG.VERSION,message:'Đã chuyển cột B thành Tên học sinh và cột C thành studentId.'}}
function testApi(){return{ok:true,version:CONFIG.VERSION,spreadsheetId:CONFIG.SPREADSHEET_ID,className:CONFIG.CLASS_NAME,students:readPhysicalStudents_().length,timestamp:new Date().toISOString()}}